In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Train and Test sets

from google.colab import drive
drive.mount('/content/drive')

import os

# Set the search parameters
filename = "3.xlsx"
search_path = '/content/drive/My Drive'

# Search for the file
for root, dirs, files in os.walk(search_path):
    if filename in files:
        file_path = os.path.join(root, filename)
        break

import pandas as pd

# Load the XLSX file into a DataFrame
df = pd.read_excel(file_path)

## Training set (imputing and normalizing)

In [4]:
df = pd.read_excel("3.xlsx")

In [5]:
df.head()

,Patient_Hospital,Outcome_InhospitalMortality,Outcome_ICUadmission,TM_S_Intubation,TM_S_Dialysis,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,Hospital1,0.0,1,1,1,0.0,1.0,1,1,0,...,NaN,140.0,4.0,181.0,62.0,661.0,32.6,10.9,1.00,33.0
1,Hospital1,0.0,1,1,0,NaN,1.0,1,1,0,...,1.1,139.0,3.5,98.0,30.0,179.0,37.6,10.8,0.99,44.0
2,Hospital1,0.0,1,0,1,NaN,1.0,0,1,0,...,0.9,138.0,4.2,99.0,29.0,1956.0,27.4,12.1,1.11,50.0
3,Hospital1,1.0,1,0,0,NaN,1.0,0,1,1,...,1.2,137.0,4.7,139.0,20.0,30.0,29.1,14.2,1.31,71.0
4,Hospital1,1.0,1,0,0,NaN,1.0,0,1,1,...,1.2,137.0,4.7,139.0,20.0,30.0,29.1,14.2,1.31,71.0

In [6]:
# ooutcome columns: 1.are Outcome_InhospitalMortality 2.TM_S_Intubation  3.Outcome_ICUadmission  4.TM_S_Dialysis
df = df.dropna(subset=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])

In [7]:
#inja oomadim va external validation ro freeze kardim
df_internal_validation = df[df['Patient_Hospital']!="Hospital2"]
df_external_validation = df[df['Patient_Hospital']=="Hospital2"]
df_internal_validation = df_internal_validation.drop(columns=['Patient_Hospital'])
df_external_validation = df_external_validation.drop(columns=['Patient_Hospital'])

In [8]:
#df.to_excel("excluding NAN.xlsx", index=False)

In [9]:
#inja train test split kardim va target variable ro jodakardim
# Define features (X) and target variable (y)
X = df_internal_validation.drop(columns=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])
y  = df_internal_validation[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]
# Perform the train-test split (adjust the test_size as needed)
X_train , X_test , y_train , y_test = train_test_split(X,y , test_size = 0.2 , random_state = 42)

In [10]:
y_train

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
1513,1.0,0,0,0
216,0.0,0,0,0
5163,0.0,0,0,1
6924,1.0,0,0,0
421,0.0,0,1,0
...,...,...,...,...
6007,1.0,0,0,0
6173,1.0,0,0,0
860,1.0,0,0,0
9089,1.0,0,0,0
8082,1.0,0,0,0

In [11]:
X_train

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
1513,NaN,0.0,0,1,0,0,0,0,0.0,0,...,NaN,134.0,3.8,190.0,62.0,40.0,30.100000,11.400000,1.05,38.0
216,10.0,0.0,0,0,0,0,0,1,0.0,0,...,3.4,128.0,6.2,189.0,97.0,98.0,38.500000,12.000000,0.89,89.0
5163,10.0,0.0,0,0,0,0,0,1,1.0,0,...,2.7,125.0,3.8,197.0,52.0,538.0,35.900002,19.200001,1.78,80.0
6924,NaN,1.0,0,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0
421,0.0,0.0,1,1,0,0,0,0,0.0,0,...,1.4,134.0,5.1,201.0,7.0,191.0,20.300000,12.900000,1.19,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6007,NaN,1.0,0,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0
6173,NaN,0.0,1,1,1,1,1,0,0.0,0,...,0.8,140.0,4.5,219.0,26.0,40.0,25.299999,10.900000,1.00,46.0
860,NaN,1.0,0,0,0,0,0,0,0.0,0,...,NaN,136.0,3.7,NaN,NaN,NaN,NaN,NaN,NaN,62.0
9089,NaN,1.0,0,0,0,0,0,1,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0
8082,NaN,1.0,1,1,0,0,1,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0

In [12]:
#inja miaim va data haye categorical va numerical ro moshakhas mikonim ke bade knn categorical ha ro round konim
cat_col=[]
num_col=[]
for i in range(len(X_train.columns)):
    if i <=52:
        cat_col.append(X_train.columns[i])
    else:
        num_col.append(X_train.columns[i])

In [13]:
from sklearn.impute import KNNImputer
X_train_array  =X_train.to_numpy()
imputer = KNNImputer(n_neighbors=5, weights="uniform")
imputed = imputer.fit_transform(X_train_array)

In [14]:
df_imputed = pd.DataFrame(imputed)
df_imputed.columns=pd.DataFrame(X_train).columns.tolist()

In [15]:
df_imputed

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,5.4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.000,134.0,3.800,190.0,62.0,40.0,30.100000,11.400000,1.050,38.0
1,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,3.400,128.0,6.200,189.0,97.0,98.0,38.500000,12.000000,0.890,89.0
2,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,2.700,125.0,3.800,197.0,52.0,538.0,35.900002,19.200001,1.780,80.0
3,5.6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.404,134.8,4.020,199.2,77.6,1794.6,29.620000,12.980000,1.142,66.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.400,134.0,5.100,201.0,7.0,191.0,20.300000,12.900000,1.190,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6113,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.720,137.8,9.900,220.0,45.4,3417.4,28.260000,37.780000,3.100,34.0
6114,5.2,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.800,140.0,4.500,219.0,26.0,40.0,25.299999,10.900000,1.000,46.0
6115,5.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.380,136.0,3.700,204.6,57.0,277.2,34.120000,13.080000,1.148,62.0
6116,5.8,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.480,139.8,3.840,166.2,44.6,1786.8,22.980000,12.560000,1.158,85.0
6117,5.4,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,2.020,138.2,4.328,202.6,47.2,2031.2,25.980000,12.840000,1.146,50.0

In [16]:
for i in cat_col:
    df_imputed[[i]] = df_imputed[[i]].round()

In [17]:
df_imputed.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [18]:
df_imputed.shape

(6118, 76)

In [19]:
y_train.shape

(6118, 4)

In [20]:
#miaim x , y ro be ham michaboonim ta betonim normilize konim
df_before_normalize = pd.concat([df_imputed , y_train], axis=1)

In [21]:
arr_tain =df_imputed.to_numpy()

In [22]:
from sklearn import preprocessing
transform = preprocessing.StandardScaler()
df_normalize = transform.fit_transform(arr_tain)
df_normalize =pd.DataFrame(df_normalize)
df_normalize.columns = df_imputed.columns.tolist()

In [23]:
X_train = df_normalize
y_train = df_before_normalize[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]

In [24]:
X_train

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,-0.276680,-1.073643,-0.964980,0.831820,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,0.582338,-0.648257,-0.175146,-0.177518,0.000308,-0.500660,-0.200713,-0.267870,-0.179127,-0.992162
1,3.033314,-1.073643,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,1.318554,-0.307016,-0.159078,...,0.771789,-1.840350,-0.023451,-0.184953,0.027164,-0.446365,-0.033882,-0.241880,-0.187715,1.496371
2,3.033314,-1.073643,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,1.318554,3.257163,-0.159078,...,0.440249,-2.436396,-0.175146,-0.125471,-0.007365,-0.034479,-0.085520,0.069998,-0.139942,1.057218
3,0.385318,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,-0.173572,-0.489311,-0.161241,-0.109114,0.012278,1.141832,-0.210247,-0.199430,-0.174188,0.374091
4,-3.586675,-1.073643,1.036291,0.831820,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,-0.175466,-0.648257,-0.092978,-0.095730,-0.041893,-0.359308,-0.395350,-0.202895,-0.171612,-0.796983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6113,1.047317,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,0.449722,0.106735,0.210412,0.045540,-0.012429,2.660945,-0.237258,0.874816,-0.069088,-1.187341
6114,-0.276680,-1.073643,1.036291,0.831820,1.178125,1.724908,1.568569,-0.758406,-0.307016,-0.159078,...,-0.459643,0.543836,-0.130902,0.038104,-0.027314,-0.500660,-0.296046,-0.289528,-0.181810,-0.601804
6115,-0.276680,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,0.288689,-0.250893,-0.181467,-0.068963,-0.003528,-0.278615,-0.120873,-0.195098,-0.173866,0.178912
6116,0.385318,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,1.318554,3.257163,-0.159078,...,-0.137576,0.504099,-0.172618,-0.354477,-0.013043,1.134530,-0.342123,-0.217623,-0.173329,1.301192
6117,-0.276680,0.931408,1.036291,0.831820,-0.848806,-0.579741,1.568569,-0.758406,-0.307016,-0.159078,...,0.118183,0.186208,-0.141773,-0.083834,-0.011048,1.363315,-0.282540,-0.205494,-0.173974,-0.406625

In [25]:
y_train

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,0.0,0,0,0
2,0.0,0,0,1
3,1.0,0,0,0
4,0.0,0,1,0
...,...,...,...,...
6113,1.0,0,0,0
6114,1.0,0,0,0
6115,1.0,0,0,0
6116,1.0,0,0,0
6117,1.0,0,0,0

In [26]:
y.value_counts("Outcome_InhospitalMortality")

Outcome_InhospitalMortality
1.0    6115
0.0    1533
Name: count, dtype: int64

In [27]:
y.value_counts("TM_S_Intubation")

TM_S_Intubation
0    7012
1     636
Name: count, dtype: int64

In [28]:
y.value_counts("Outcome_ICUadmission")

Outcome_ICUadmission
0    6387
1    1261
Name: count, dtype: int64

In [29]:
y.value_counts("TM_S_Dialysis")

TM_S_Dialysis
0    7384
1     264
Name: count, dtype: int64

## Test set (imputing and normalizing)

In [30]:
y_test

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
3265,1.0,0,0,0
6728,1.0,0,0,0
2892,1.0,0,0,0
3984,1.0,0,0,0
1221,1.0,0,0,0
...,...,...,...,...
7528,1.0,0,0,0
7526,0.0,0,0,0
1192,1.0,0,0,0
3964,1.0,0,1,0
5508,1.0,0,0,0

In [31]:
X_test

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
3265,NaN,1.0,1,1,1,0,1,0,0.0,0,...,1.02,136.0,3.8,278.0,42.0,71.0,33.0,16.1,1.40,53.0
6728,NaN,0.0,0,0,0,0,0,0,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0
2892,NaN,0.0,1,1,1,1,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0
3984,NaN,1.0,0,0,1,1,0,0,0.0,0,...,3.49,135.0,3.6,221.0,34.0,218.0,40.0,13.0,1.00,54.0
1221,NaN,1.0,0,1,0,0,1,0,0.0,0,...,1.20,137.0,3.9,100.0,17.0,232.0,35.6,14.0,1.28,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7528,NaN,1.0,1,1,1,1,1,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0
7526,NaN,1.0,0,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.0
1192,NaN,0.0,1,1,1,0,0,1,0.0,0,...,1.00,133.0,3.8,184.0,14.0,259.0,25.8,10.6,0.97,75.0
3964,10.0,1.0,0,1,1,1,1,0,0.0,0,...,NaN,139.0,4.0,153.0,NaN,124.0,38.0,13.0,1.00,50.0
5508,NaN,0.0,1,1,0,0,1,1,0.0,0,...,0.90,140.0,5.1,NaN,NaN,102.0,NaN,NaN,NaN,43.0

In [32]:
#inja miaim va data haye categorical va numerical ro moshakhas mikonim ke bade knn categorical ha ro round konim
cat_col=[]
num_col=[]
for i in range(len(X_test.columns)):
    if i <=52:
        cat_col.append(X_test.columns[i])
    else:
        num_col.append(X_test.columns[i])

In [33]:
from sklearn.impute import KNNImputer
X_test_array  =X_test.to_numpy()
imputer = KNNImputer(n_neighbors=5, weights="uniform")
imputed_test = imputer.fit_transform(X_test_array)

In [34]:
df_imputed_test = pd.DataFrame(imputed_test)
df_imputed_test.columns=pd.DataFrame(X_test).columns.tolist()

In [35]:
df_imputed_test

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,6.4,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.020,136.0,3.80,278.0,42.0,71.0,33.00,16.10,1.400,53.0
1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.310,138.0,4.12,216.6,36.0,142.0,25.64,12.32,1.200,72.0
2,4.6,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.440,138.8,4.00,247.6,41.2,116.6,25.64,11.54,1.044,75.0
3,7.6,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,3.490,135.0,3.60,221.0,34.0,218.0,40.00,13.00,1.000,54.0
4,6.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.200,137.0,3.90,100.0,17.0,232.0,35.60,14.00,1.280,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,3.2,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.340,138.2,4.18,230.4,44.6,190.0,29.40,12.90,1.188,73.0
1526,4.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.340,135.6,4.12,336.4,28.8,212.6,23.86,11.98,1.100,83.0
1527,6.8,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.000,133.0,3.80,184.0,14.0,259.0,25.80,10.60,0.970,75.0
1528,10.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.124,139.0,4.00,153.0,27.2,124.0,38.00,13.00,1.000,50.0
1529,6.4,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.900,140.0,5.10,154.0,38.2,102.0,26.60,11.96,1.060,43.0

In [36]:
for i in cat_col:
    df_imputed_test[[i]] = df_imputed_test[[i]].round()

In [37]:
df_imputed_test.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)

In [38]:
df_imputed_test.shape

(1530, 76)

In [39]:
y_test.shape

(1530, 4)

In [40]:
#miaim x , y ro be ham michaboonim ta betonim normilize konim
df_test_before_normalize = pd.concat([df_imputed_test , y_test], axis=1)

In [41]:
df_test_before_normalize.shape

(1530, 80)

In [42]:
arr =df_test_before_normalize.to_numpy()

In [43]:
arr

array([[ 6.,  1.,  1., ...,  0.,  0.,  0.],
       [ 4.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 7.,  0.,  1., ...,  0.,  0.,  0.],
       [10.,  1.,  0., ...,  0.,  1.,  0.],
       [ 6.,  0.,  1., ...,  0.,  0.,  0.]])

In [44]:
from sklearn import preprocessing
transform = preprocessing.StandardScaler()
df_test_normalize = transform.fit_transform(arr)
df_test_normalize =pd.DataFrame(df_test_normalize)
df_test_normalize.columns = df_internal_validation.columns.tolist()
df_test_normalize

,Outcome_InhospitalMortality,Outcome_ICUadmission,TM_S_Intubation,TM_S_Dialysis,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,0.273437,0.923201,1.015811,0.858291,1.149652,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,...,0.197160,-0.372111,-0.134902,-0.054534,-0.167261,-0.319589,0.488740,-0.29173,-0.439827,-0.172075
1,-0.826059,-1.083188,-0.984435,-1.165106,-0.869828,-0.622195,-0.614115,-0.760886,3.295522,-0.128885,...,-0.098909,-0.247149,-0.267645,-0.231791,-0.178905,0.722315,0.488740,-0.29173,-0.439827,-0.172075
2,-0.276311,-1.083188,1.015811,0.858291,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,...,0.157684,-0.291854,-0.267645,-0.268368,-0.187986,0.886826,0.488740,-0.29173,-0.439827,-0.172075
3,1.372933,0.923201,-0.984435,-1.165106,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,...,-0.197599,-0.113387,-0.008651,-0.199903,-0.190548,-0.264752,0.488740,-0.29173,-0.439827,-0.172075
4,0.273437,0.923201,-0.984435,0.858291,-0.869828,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,...,-1.036461,-0.088747,-0.088009,-0.153010,-0.174247,-0.484100,0.488740,-0.29173,-0.439827,-0.172075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,-1.375807,0.923201,1.015811,0.858291,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,...,0.325457,-0.162668,-0.199830,-0.204593,-0.179603,0.777152,0.488740,-0.29173,-0.439827,-0.172075
1526,-0.826059,0.923201,-0.984435,0.858291,-0.869828,-0.622195,-0.614115,-0.760886,-0.303442,-0.128885,...,-0.454192,-0.122892,-0.299748,-0.247734,-0.184726,1.325522,-2.046079,-0.29173,-0.439827,-0.172075
1527,0.823185,-1.083188,1.015811,0.858291,1.149652,-0.622195,-0.614115,1.314257,-0.303442,-0.128885,...,-1.184496,-0.041226,-0.264759,-0.312447,-0.192294,0.886826,0.488740,-0.29173,-0.439827,-0.172075
1528,2.472429,0.923201,-0.984435,0.858291,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,...,-0.533144,-0.278830,-0.044723,-0.199903,-0.190548,-0.484100,0.488740,-0.29173,2.273622,-0.172075
1529,0.273437,-1.083188,1.015811,0.858291,-0.869828,-0.622195,1.628358,1.314257,-0.303442,-0.128885,...,0.009650,-0.317551,-0.250330,-0.248672,-0.187055,-0.867959,0.488740,-0.29173,-0.439827,-0.172075

In [45]:
X_test = df_test_normalize.drop(columns=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])
y_test = df_test_before_normalize[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]

In [46]:
X_test

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,1.149652,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,2.279108,...,0.197160,-0.372111,-0.134902,-0.054534,-0.167261,-0.319589,0.488740,-0.29173,-0.439827,-0.172075
1,-0.869828,-0.622195,-0.614115,-0.760886,3.295522,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-0.098909,-0.247149,-0.267645,-0.231791,-0.178905,0.722315,0.488740,-0.29173,-0.439827,-0.172075
2,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,0.157684,-0.291854,-0.267645,-0.268368,-0.187986,0.886826,0.488740,-0.29173,-0.439827,-0.172075
3,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-0.197599,-0.113387,-0.008651,-0.199903,-0.190548,-0.264752,0.488740,-0.29173,-0.439827,-0.172075
4,-0.869828,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-1.036461,-0.088747,-0.088009,-0.153010,-0.174247,-0.484100,0.488740,-0.29173,-0.439827,-0.172075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,0.325457,-0.162668,-0.199830,-0.204593,-0.179603,0.777152,0.488740,-0.29173,-0.439827,-0.172075
1526,-0.869828,-0.622195,-0.614115,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,2.046079,-0.438768,...,-0.454192,-0.122892,-0.299748,-0.247734,-0.184726,1.325522,-2.046079,-0.29173,-0.439827,-0.172075
1527,1.149652,-0.622195,-0.614115,1.314257,-0.303442,-0.128885,-0.096098,-0.106,2.046079,2.279108,...,-1.184496,-0.041226,-0.264759,-0.312447,-0.192294,0.886826,0.488740,-0.29173,-0.439827,-0.172075
1528,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-0.533144,-0.278830,-0.044723,-0.199903,-0.190548,-0.484100,0.488740,-0.29173,2.273622,-0.172075
1529,-0.869828,-0.622195,1.628358,1.314257,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,0.009650,-0.317551,-0.250330,-0.248672,-0.187055,-0.867959,0.488740,-0.29173,-0.439827,-0.172075

In [47]:
y_test

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,1.0,0,0,0
2,1.0,0,0,0
3,1.0,0,0,0
4,1.0,0,0,0
...,...,...,...,...
1525,1.0,0,0,0
1526,0.0,0,0,0
1527,1.0,0,0,0
1528,1.0,0,1,0
1529,1.0,0,0,0

>>>Now dataset is cleaned and normalized

In [48]:
y_train

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,0.0,0,0,0
2,0.0,0,0,1
3,1.0,0,0,0
4,0.0,0,1,0
...,...,...,...,...
6113,1.0,0,0,0
6114,1.0,0,0,0
6115,1.0,0,0,0
6116,1.0,0,0,0
6117,1.0,0,0,0

In [49]:
y_train_Mortality =pd.DataFrame(y_train.loc[ : ,'Outcome_InhospitalMortality'])

In [50]:
y_train_Mortality

      Outcome_InhospitalMortality
0                             1.0
1                             0.0
2                             0.0
3                             1.0
4                             0.0
...                           ...
6113                          1.0
6114                          1.0
6115                          1.0
6116                          1.0
6117                          1.0

[6118 rows x 1 columns]

In [51]:
y_test

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,1.0,0,0,0
2,1.0,0,0,0
3,1.0,0,0,0
4,1.0,0,0,0
...,...,...,...,...
1525,1.0,0,0,0
1526,0.0,0,0,0
1527,1.0,0,0,0
1528,1.0,0,1,0
1529,1.0,0,0,0

In [52]:
y_test_Mortality =pd.DataFrame(y_train.loc[ : ,'Outcome_InhospitalMortality'])

## data selection Mortality and ICU

In [53]:
from sklearn.linear_model import Lasso

def lasso_MO_ICU(X_train ,y_train,X_test):
    # Perform feature selection using LASSO on the training set
    lasso = Lasso(alpha=0.1)
    lasso.fit(X_train, y_train)

    # Get the absolute coefficients and sort them
    absolute_coeffs = np.abs(lasso.coef_)
    sorted_indices = np.argsort(absolute_coeffs)[::-1]
    
    
    X_train = X  = pd.DataFrame(X_train)
    X_test = X  = pd.DataFrame(X_test)
    # Select the top 2 features with the highest coefficients
    selected_features = X_train.columns[sorted_indices[:45]]

    # Apply feature selection to both the training and test sets
    X_train_selected_Mortality_ICU = X_train[selected_features]
    X_test_selected_Mortality_ICU = X_test[selected_features]
    
    return (pd.DataFrame(X_train_selected_Mortality_ICU), pd.DataFrame(X_test_selected_Mortality_ICU))

## data selection Intubation and Dialysis

In [54]:
# ino aslan mindazim oon var va estefade nemikonim

from sklearn.linear_model import Lasso

def lasso_In_Dia(X_train ,y_train_Intubation):
    # Perform feature selection using LASSO on the training set
    lasso = Lasso(alpha=0.1)
    lasso.fit(X_train, y_train_Mortality)

    # Get the absolute coefficients and sort them
    absolute_coeffs = np.abs(lasso.coef_)
    sorted_indices = np.argsort(absolute_coeffs)[::-1]

    # Select the top 2 features with the highest coefficients
    selected_features = X_train.columns[sorted_indices[:10]]

    # Apply feature selection to both the training and test sets
    X_train_selected_In_Dia = X_train[selected_features]
    X_test_selected_In_Dia = X_test[selected_features]
    
    return X_train_selected_In_Dia, X_test_selected_In_Dia

# Undersampling and and Oversampling\

using **SMOTETomek**

In [129]:
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks
from imblearn.combine import SMOTEENN

def balancing_dataset(X_train,y_train , X_test , y_test):
    
    tl = SMOTEENN(random_state=42)
    X_resampled_train , y_resampled_train = tl.fit_resample(X_train,y_train)
    X_resampled_test , y_resampled_test = tl.fit_resample(X_test,y_test)
    
    return (X_resampled_train, y_resampled_train,X_resampled_test , y_resampled_test )

# experimenting different models on dataset

In [56]:

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [57]:
def plot_confusion_matrix(y,y_predict):
    "this function plots the confusion matrix"
    from sklearn.metrics import confusion_matrix

    cm = confusion_matrix(y, y_predict)
    ax= plt.subplot()
    sns.heatmap(cm, annot=True, ax = ax); 
    ax.set_xlabel('Predicted labels')
    ax.set_ylabel('True labels')
    ax.set_title('Confusion Matrix');
    ax.xaxis.set_ticklabels(['did not hapen', 'happend']); ax.yaxis.set_ticklabels(['did not hapen', 'happend'])

In [58]:
X_train = np.array(X_train)
X_test = np.array(X_test)

## Logistic Regression

In [59]:

#remember to consider x_test and y_test for each model

In [60]:
y_train_Outcome_InhospitalMortality = np.array(y_train['Outcome_InhospitalMortality'].tolist())
y_test_Outcome_InhospitalMortality = np.array(y_test['Outcome_InhospitalMortality'].tolist())

In [61]:
y_train_Outcome_InhospitalMortality.shape

(6118,)

In [62]:
X_train.shape

(6118, 76)

# define hyperparameters to tune
parameters_lr ={}

# define the model
lr = LogisticRegression(random_state = 12345)

# define the grid search object
grid_search_lr = GridSearchCV(
    estimator = lr,
    param_grid = parameters_lr,
    cv = 10,
    n_jobs=-1
)
# execute search
logreg_cv = grid_search_lr.fit(X_train,y_train_Outcome_InhospitalMortality)

best_classifier_lr = logreg_cv.best_estimator_

y_predicted_Mortality_lr = best_classifier_lr.predict(X_test)

from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score ,f1_score

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)

Logistic_Regression = {}
Logistic_Regression["accuracy"]= accuracy
Logistic_Regression["precision"]= precision
Logistic_Regression["recall"]= recall
Logistic_Regression["specificity"]= accuracy
Logistic_Regression["f1"]= f1


y_plot = {}
y_plot["y_true"]= y_train_Outcome_InhospitalMortality
y_plot["y_predicted"]=y_test_Outcome_InhospitalMortality

In [63]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)
def logistic_regression_classifier(X_train, y_train, X_test, y_test):

    parameters_lr = {}


    lr = LogisticRegression(random_state=12345)


    grid_search_lr = GridSearchCV(
        estimator=lr,
        param_grid=parameters_lr,
        cv=5,
        n_jobs=-1
    )

    logreg_cv = grid_search_lr.fit(X_train, y_train)

    
    best_classifier_lr = logreg_cv.best_estimator_

 
    y_predicted_Mortality_lr = best_classifier_lr.predict(X_test)

 
    accuracy = accuracy_score(y_test, y_predicted_Mortality_lr)
    cm = confusion_matrix(y_test, y_predicted_Mortality_lr)
    precision = precision_score(y_test, y_predicted_Mortality_lr)
    recall = recall_score(y_test, y_predicted_Mortality_lr)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_lr)


    Logistic_Regression = {}
    Logistic_Regression["accuracy"] = accuracy
    Logistic_Regression["precision"] = precision
    Logistic_Regression["recall"] = recall
    Logistic_Regression["specificity"] = specificity
    Logistic_Regression["f1"] = f1

    y_plot = {}
    y_plot["y_true"] = y_train
    y_plot["y_predicted"] = y_predicted_Mortality_lr
    
    Logistic_Regression = (Logistic_Regression, y_plot)
    
    return Logistic_Regression

## SVM

from sklearn import svm
svm = svm.SVC(random_state = 1234)

# define hyperparameters to tune
parameters_svm = {}

# define the grid search object
grid_search_svm = GridSearchCV(
    estimator = svm,
    param_grid = parameters_svm,
    cv = 10
)
# execute search
svm_cv = grid_search_svm.fit(X_train,y_train_Outcome_InhospitalMortality)

best_classifier_svm = svm_cv.best_estimator_

y_predicted_Mortality_svm = best_classifier_svm.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)

svm = {}
svm["accuracy"]= accuracy
svm["precision"]= precision
svm["recall"]= recall
svm["specificity"]= accuracy
svm["f1"]= f1

y_plot = {}
y_plot["y_true"]= y_train_Outcome_InhospitalMortality
y_plot["y_predicted"]=y_test_Outcome_InhospitalMortality

In [64]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_svm(X_train, y_train, X_test, y_test):

    svm_classifier = svm.SVC(random_state=1234)


    parameters_svm = {}


    grid_search_svm = GridSearchCV(
        estimator=svm_classifier,
        param_grid=parameters_svm,
        cv=5
    )
    
   
    svm_cv = grid_search_svm.fit(X_train, y_train)

 
    best_classifier_svm = svm_cv.best_estimator_


    y_predicted_Mortality_svm = best_classifier_svm.predict(X_test)

   
    accuracy = accuracy_score(y_test, y_predicted_Mortality_svm)
    cm = confusion_matrix(y_test, y_predicted_Mortality_svm)
    precision = precision_score(y_test, y_predicted_Mortality_svm)
    recall = recall_score(y_test, y_predicted_Mortality_svm)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_svm)

    svm_results = {}
    svm_results["accuracy"] = accuracy
    svm_results["precision"] = precision
    svm_results["recall"] = recall
    svm_results["specificity"] = specificity
    svm_results["f1"] = f1

  
    y_plot = {}
    y_plot["y_true"] = y_train  
    y_plot["y_predicted"] = y_predicted_Mortality_svm

    svm_results = (svm_results, y_plot)
    
    return svm_results

## Decision tree

# define hyperparameters to tune
parameters_tree = {}

# define the model
tree = DecisionTreeClassifier(random_state = 12345)

# define the grid search object
grid_search_tree = GridSearchCV(
    estimator = tree,
    param_grid = parameters_tree,
    cv = 10
)
# execute search
tree_cv = grid_search_tree.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_tree = tree_cv.best_estimator_

y_predicted_Mortality_tree = best_classifier_tree.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)

tree = {}
tree["accuracy"]= accuracy
tree["precision"]= precision
tree["recall"]= recall
tree["specificity"]= accuracy
tree["f1"]= f1

In [65]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_tree(X_train, y_train, X_test, y_test):

    parameters_tree = {}

 
    tree = DecisionTreeClassifier(random_state=12345)

 
    grid_search_tree = GridSearchCV(
        estimator=tree,
        param_grid=parameters_tree,
        cv=5
    )
    

    tree_cv = grid_search_tree.fit(X_train, y_train)

  
    best_classifier_tree = tree_cv.best_estimator_

 
    y_predicted_Mortality_tree = best_classifier_tree.predict(X_test)

 
    accuracy = accuracy_score(y_test, y_predicted_Mortality_tree)
    cm = confusion_matrix(y_test, y_predicted_Mortality_tree)
    precision = precision_score(y_test, y_predicted_Mortality_tree)
    recall = recall_score(y_test, y_predicted_Mortality_tree)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_tree)

  
    tree_results = {}
    tree_results["accuracy"] = accuracy
    tree_results["precision"] = precision
    tree_results["recall"] = recall
    tree_results["specificity"] = specificity
    tree_results["f1"] = f1


    y_plot = {}
    y_plot["y_true"] = y_train 
    y_plot["y_predicted"] = y_predicted_Mortality_tree

    tree_results = (tree_results, y_plot)
    
    return tree_results

## KNN

# define hyperparameters to tune
parameters_knn = {}

# define the model
knn = KNeighborsClassifier()

# define the grid search object
grid_search_knn = GridSearchCV(
    estimator = knn,
    param_grid = parameters_knn,
    cv = 10
)
# execute search
knn_cv = grid_search_knn.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_knn = knn_cv.best_estimator_

y_predicted_Mortality_Knn = best_classifier_knn.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)

Knn = {}
Knn["accuracy"]= accuracy
Knn["precision"]= precision
Knn["recall"]= recall
Knn["specificity"]= accuracy
Knn["f1"]= f1

In [66]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_knn(X_train, y_train, X_test, y_test):

    parameters_knn = {}

 
    knn = KNeighborsClassifier()


    grid_search_knn = GridSearchCV(
        estimator=knn,
        param_grid=parameters_knn,
        cv=5
    )
    

    knn_cv = grid_search_knn.fit(X_train, y_train)

    best_classifier_knn = knn_cv.best_estimator_

    y_predicted_Mortality_knn = best_classifier_knn.predict(X_test)

    accuracy = accuracy_score(y_test, y_predicted_Mortality_knn)
    cm = confusion_matrix(y_test, y_predicted_Mortality_knn)
    precision = precision_score(y_test, y_predicted_Mortality_knn)
    recall = recall_score(y_test, y_predicted_Mortality_knn)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_knn)

    knn_results = {}
    knn_results["accuracy"] = accuracy
    knn_results["precision"] = precision
    knn_results["recall"] = recall
    knn_results["specificity"] = specificity
    knn_results["f1"] = f1


    y_plot = {}
    y_plot["y_true"] = y_train  
    y_plot["y_predicted"] = y_predicted_Mortality_knn

    knn_results = (knn_results, y_plot)
    
    return knn_results

In [67]:
X_train

array([[-0.27668045, -1.07364303, -0.96498024, ..., -0.26786983,
        -0.17912663, -0.99216208],
       [ 3.03331364, -1.07364303, -0.96498024, ..., -0.24188002,
        -0.18771498,  1.49637106],
       [ 3.03331364, -1.07364303, -0.96498024, ...,  0.06999779,
        -0.13994226,  1.05721816],
       ...,
       [-0.27668045,  0.93140827, -0.96498024, ..., -0.19509835,
        -0.17386626,  0.17891234],
       [ 0.38531837,  0.93140827, -0.96498024, ..., -0.21762285,
        -0.17332949,  1.30119199],
       [-0.27668045,  0.93140827,  1.03629065, ..., -0.20549427,
        -0.17397362, -0.40662487]])

In [68]:
y_test['TM_S_Intubation']

0       0
1       0
2       0
3       0
4       0
       ..
1525    0
1526    0
1527    0
1528    0
1529    0
Name: TM_S_Intubation, Length: 1530, dtype: int64

In [69]:
X_test

array([[ 1.14965192, -0.62219452,  1.62835847, ..., -0.29172998,
        -0.43982694, -0.17207467],
       [-0.86982849, -0.62219452, -0.61411539, ..., -0.29172998,
        -0.43982694, -0.17207467],
       [ 1.14965192,  1.60721441, -0.61411539, ..., -0.29172998,
        -0.43982694, -0.17207467],
       ...,
       [ 1.14965192, -0.62219452, -0.61411539, ..., -0.29172998,
        -0.43982694, -0.17207467],
       [ 1.14965192,  1.60721441,  1.62835847, ..., -0.29172998,
         2.27362152, -0.17207467],
       [-0.86982849, -0.62219452,  1.62835847, ..., -0.29172998,
        -0.43982694, -0.17207467]])

In [70]:
y_train['TM_S_Intubation']

0       0
1       0
2       0
3       0
4       0
       ..
6113    0
6114    0
6115    0
6116    0
6117    0
Name: TM_S_Intubation, Length: 6118, dtype: int64

In [71]:
np.array(y_train['TM_S_Intubation'])

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [72]:
train_and_evaluate_knn(np.array(X_train),np.array(y_train['TM_S_Intubation']), np.array(X_test), np.array(y_test['TM_S_Intubation']))

({'accuracy': 0.9183006535947712,
  'precision': 0.14285714285714285,
  'recall': 0.008333333333333333,
  'specificity': 0.008333333333333333,
  'f1': 0.015748031496062992},
 {'y_true': array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
  'y_predicted': array([0, 0, 0, ..., 0, 0, 0], dtype=int64)})

## Random forest

from sklearn.ensemble import RandomForestClassifier

parameters_forest = {}

forest = RandomForestClassifier

grid_search_forest = GridSearchCV(
    estimator = forest,
    param_grid = parameters_forest,
    cv = 10
)
# execute search
forest_cv = grid_search_knn.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_forest = forest_cv.best_estimator_

y_predicted_Mortality_forest = best_classifier_forest.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)

forest = {}
forest["accuracy"]= accuracy
forest["precision"]= precision
forest["recall"]= recall
forest["specificity"]= accuracy
forest["f1"]= f1

In [73]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_forest(X_train, y_train, X_test, y_test):
    parameters_forest = {}


    forest = RandomForestClassifier()


    grid_search_forest = GridSearchCV(
        estimator=forest,
        param_grid=parameters_forest,
        cv=5
    )
    

    forest_cv = grid_search_forest.fit(X_train, y_train)

    best_classifier_forest = forest_cv.best_estimator_

    y_predicted_Mortality_forest = best_classifier_forest.predict(X_test)


    accuracy = accuracy_score(y_test, y_predicted_Mortality_forest)
    cm = confusion_matrix(y_test, y_predicted_Mortality_forest)
    precision = precision_score(y_test, y_predicted_Mortality_forest)
    recall = recall_score(y_test, y_predicted_Mortality_forest)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_forest)


    forest_results = {}
    forest_results["accuracy"] = accuracy
    forest_results["precision"] = precision
    forest_results["recall"] = recall
    forest_results["specificity"] = specificity
    forest_results["f1"] = f1

    y_plot = {}
    y_plot["y_true"] = y_train
    y_plot["y_predicted"] = y_predicted_Mortality_forest

    return forest_results, y_plot

## Neural Network

from sklearn.neural_network import MLPClassifier

parameters_neural = {}

neural = MLPClassifier()

grid_search_neural = GridSearchCV(
    estimator = neural,
    param_grid = parameters_neural,
    cv = 10
)

neural_cv = grid_search_neural.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_neural = neural_cv.best_estimator_

y_predicted_Mortality_neural =best_classifier_neural.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)

neural = {}
neural["accuracy"]= accuracy
neural["precision"]= precision
neural["recall"]= recall
neural["specificity"]= accuracy
neural["f1"]= f1

In [74]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_neural(X_train, y_train, X_test, y_test):

    parameters_neural = {}


    neural = MLPClassifier()

    grid_search_neural = GridSearchCV(
        estimator=neural,
        param_grid=parameters_neural,
        cv=5
    )
    

    neural_cv = grid_search_neural.fit(X_train, y_train)

   
    best_classifier_neural = neural_cv.best_estimator_

    
    y_predicted_Mortality_neural = best_classifier_neural.predict(X_test)

    accuracy = accuracy_score(y_test, y_predicted_Mortality_neural)
    cm = confusion_matrix(y_test, y_predicted_Mortality_neural)
    precision = precision_score(y_test, y_predicted_Mortality_neural)
    recall = recall_score(y_test, y_predicted_Mortality_neural)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_neural)

 
    neural_results = {}
    neural_results["accuracy"] = accuracy
    neural_results["precision"] = precision
    neural_results["recall"] = recall
    neural_results["specificity"] = specificity
    neural_results["f1"] = f1

    
    y_plot = {}
    y_plot["y_true"] = y_train  
    y_plot["y_predicted"] = y_predicted_Mortality_neural

    return neural_results, y_plot

## XGboost

from xgboost import XGBClassifier
# Define a parameter grid to search through
parameters_boost = {}

# Create an XGBoost classifier
boost = XGBClassifier()

grid_search_boost = GridSearchCV(
    estimator = boost,
    param_grid = parameters_boost,
    cv = 10
)

boost_cv = grid_search_boost.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_boost = boost_cv.best_estimator_

y_predicted_Mortality_boost =best_classifier_boost.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)

boost = {}
boost["accuracy"]= accuracy
boost["precision"]= precision
boost["recall"]= recall
boost["specificity"]= accuracy
boost["f1"]= f1

In [75]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_boost(X_train, y_train, X_test, y_test):
  
    parameters_boost = {}

 
    boost = XGBClassifier()


    grid_search_boost = GridSearchCV(
        estimator=boost,
        param_grid=parameters_boost,
        cv=5
    )
    

    boost_cv = grid_search_boost.fit(X_train, y_train)


    best_classifier_boost = boost_cv.best_estimator_


    y_predicted_Mortality_boost = best_classifier_boost.predict(X_test)


    accuracy = accuracy_score(y_test, y_predicted_Mortality_boost)
    cm = confusion_matrix(y_test, y_predicted_Mortality_boost)
    precision = precision_score(y_test, y_predicted_Mortality_boost)
    recall = recall_score(y_test, y_predicted_Mortality_boost)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_boost)

  
    boost_results = {}
    boost_results["accuracy"] = accuracy
    boost_results["precision"] = precision
    boost_results["recall"] = recall
    boost_results["specificity"] = specificity
    boost_results["f1"] = f1


    y_plot = {}
    y_plot["y_true"] = y_train 
    y_plot["y_predicted"] = y_predicted_Mortality_boost

    return boost_results, y_plot

final_Mortality_dict={'Logistic_Regression':Logistic_Regression,
                      'svm':svm,
                      'tree':tree,
                      'Knn':Knn,
                      'forest':forest,
                      'neural':neural,
                      'boost':boost}

final_Mortality_dict

df_con = pd.DataFrame.from_dict(final_Mortality_dict, orient='index')

df_con

max(df_con['f1'])

# Final results

In [76]:
y_test.columns

Index(['Outcome_InhospitalMortality', 'TM_S_Intubation',
       'Outcome_ICUadmission', 'TM_S_Dialysis'],
      dtype='object')

In [77]:
X_train.shape

(6118, 76)

In [78]:
X_test.shape

(1530, 76)

In [79]:
y_train.shape

(6118, 4)

In [80]:
y_train_ = pd.DataFrame(y_train['TM_S_Intubation'])
y_test_ = pd.DataFrame(y_test['TM_S_Intubation'])

In [81]:
y_train_.shape

(6118, 1)

In [82]:
y_test_.shape

(1530, 1)

In [83]:

X_train, X_test = lasso_MO_ICU(pd.DataFrame(X_train), y_train_ ,X_test)

c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [84]:

X_train=np.array(X_train)
X_test=np.array(X_test)

In [85]:
X_train.shape

(6118, 45)

In [86]:
X_test.shape

(1530, 45)

In [87]:

y_train_ = np.array(y_train['TM_S_Intubation'])
y_test_ = np.array(y_test['TM_S_Intubation'])

In [88]:
y_train_.shape

(6118,)

In [89]:
y_test_.shape

(1530,)

In [90]:
X_train,y_train_ , X_test , y_test_ = balancing_dataset(X_train,y_train_ , X_test , y_test_)

In [91]:
X_train.shape

(11200, 45)

In [92]:
y_train_.shape

(11200,)

In [93]:
X_test.shape

(2818, 45)

In [94]:
y_test_.shape

(2818,)

In [130]:
list_Outcome_InhospitalMortality=[]
list_TM_S_Intubation=[]
list_Outcome_ICUadmission=[]
list_TM_S_Dialysis=[]
for i in y_test.columns:
    X_train = df_normalize
    y_train = df_before_normalize[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]
    X_test = df_test_normalize.drop(columns=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])
    y_test = df_test_before_normalize[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]
    y_train_ = pd.DataFrame(y_train[i])
    y_test_ = pd.DataFrame(y_test[i])
    X_train, X_test = lasso_MO_ICU(pd.DataFrame(X_train), y_train_ ,pd.DataFrame(X_test))
    
    X_train=np.array(X_train)
    X_test=np.array(X_test)
    
    y_train_ = np.array(y_train[i])
    y_test_ = np.array(y_test[i])
    
    X_train,y_train_ , X_test , y_test_ = balancing_dataset(X_train,y_train_ , X_test , y_test_)
    
    if i =='Outcome_InhospitalMortality':
        list_Outcome_InhospitalMortality.extend([logistic_regression_classifier(X_train, y_train_, X_test, y_test_),
                                                 train_and_evaluate_svm(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_tree(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_knn(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_forest(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_neural(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_boost(X_train, y_train_, X_test, y_test_)])
    elif i =='TM_S_Intubation':
        list_TM_S_Intubation.extend([logistic_regression_classifier(X_train, y_train_, X_test, y_test_),
                                                 train_and_evaluate_svm(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_tree(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_knn(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_forest(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_neural(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_boost(X_train, y_train_, X_test, y_test_)])
    elif i =='Outcome_ICUadmission':
        list_Outcome_ICUadmission.extend([logistic_regression_classifier(X_train, y_train_, X_test, y_test_),
                                                 train_and_evaluate_svm(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_tree(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_knn(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_forest(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_neural(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_boost(X_train, y_train_, X_test, y_test_)])
    elif i =='TM_S_Dialysis':
        list_TM_S_Dialysis.extend([logistic_regression_classifier(X_train, y_train_, X_test, y_test_),
                                                 train_and_evaluate_svm(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_tree(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_knn(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_forest(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_neural(X_train, y_train_, X_test, y_test_),
                                                train_and_evaluate_boost(X_train, y_train_, X_test, y_test_)])

c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
c:\Users\Mohammad reza\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [131]:
X_test.shape

(2969, 45)

In [132]:
X_train.shape

(10620, 45)

In [133]:
y_test_.shape

(2969,)

In [134]:
y_train_.shape

(10620,)

In [135]:
list_TM_S_Intubation

[({'accuracy': 0.5526421944332393,
   'precision': 0.6294602012808783,
   'recall': 0.4942528735632184,
   'specificity': 0.4942528735632184,
   'f1': 0.5537223340040242},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 0, 0, ..., 1, 1, 0], dtype=int64)}),
 ({'accuracy': 0.6248487293263413,
   'precision': 0.6779661016949152,
   'recall': 0.632183908045977,
   'specificity': 0.632183908045977,
   'f1': 0.654275092936803},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 0, 0, ..., 1, 0, 0], dtype=int64)}),
 ({'accuracy': 0.5655506252521177,
   'precision': 0.5648949320148331,
   'recall': 0.9849137931034483,
   'specificity': 0.9849137931034483,
   'f1': 0.7179890023566378},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
 ({'accuracy': 0.5320693828156515,
   'precision': 0.6076066790352505,
   'recall': 0.47054597701149425,
   'specificity': 0.47054597701149425,
   'f1': 0.5303643724696356},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 0, 0, ..., 1, 1, 1], dtype=int64)}),
 ({'accuracy': 0.5615167406212183,
   'precision': 0.5615167406212183,
   'recall': 1.0,
   'specificity': 1.0,
   'f1': 0.7191940067166107},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
 ({'accuracy': 0.5651472367890278,
   'precision': 0.594578313253012,
   'recall': 0.709051724137931,
   'specificity': 0.709051724137931,
   'f1': 0.6467889908256881},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 1, 1, ..., 1, 1, 0], dtype=int64)}),
 ({'accuracy': 0.5615167406212183,
   'precision': 0.5615167406212183,
   'recall': 1.0,
   'specificity': 1.0,
   'f1': 0.7191940067166107},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([1, 1, 1, ..., 1, 1, 1])})]

In [136]:
result_dic_list_Outcome_InhospitalMortality = dict(zip(['logistic_regression', 'svm', 'tree', 'knn', 'forest', 'neural', 'boost'], list_Outcome_InhospitalMortality))
result_dic_list_TM_S_Intubation = dict(zip(['logistic_regression', 'svm', 'tree', 'knn', 'forest', 'neural', 'boost'], list_TM_S_Intubation))
result_dic_list_Outcome_ICUadmission = dict(zip(['logistic_regression', 'svm', 'tree', 'knn', 'forest', 'neural', 'boost'], list_Outcome_ICUadmission))
result_dic_list_TM_S_Dialysis = dict(zip(['logistic_regression', 'svm', 'tree', 'knn', 'forest', 'neural', 'boost'], list_TM_S_Dialysis))

In [137]:
result_dic_list_Outcome_InhospitalMortality

{'logistic_regression': ({'accuracy': 0.6155124653739612,
   'precision': 0.5292207792207793,
   'recall': 0.6537433155080213,
   'specificity': 0.6537433155080213,
   'f1': 0.5849282296650719},
  {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
   'y_predicted': array([0., 1., 0., ..., 1., 1., 1.])}),
 'svm': ({'accuracy': 0.6415512465373961,
   'precision': 0.5575826681870011,
   'recall': 0.6537433155080213,
   'specificity': 0.6537433155080213,
   'f1': 0.6018461538461538},
  {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
   'y_predicted': array([0., 0., 1., ..., 1., 1., 1.])}),
 'tree': ({'accuracy': 0.5495844875346261,
   'precision': 0.04225352112676056,
   'recall': 0.004010695187165776,
   'specificity': 0.004010695187165776,
   'f1': 0.007326007326007327},
  {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
   'y_predicted': array([1., 0., 1., ..., 0., 0., 0.])}),
 'knn': ({'accuracy': 0.6271468144044321,
   'precision': 0.5389408099688473,
   'recall': 0.6938502673796791,
   'specificity': 0.6938502673796791,
   'f1': 0.6066627703097603},
  {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
   'y_predicted': array([0., 0., 0., ..., 1., 1., 1.])}),
 'forest': ({'accuracy': 0.585595567867036,
   'precision': 0.0,
   'recall': 0.0,
   'specificity': 0.0,
   'f1': 0.0},
  {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
   'y_predicted': array([0., 0., 0., ..., 0., 0., 0.])}),
 'neural': ({'accuracy': 0.5024930747922438,
   'precision': 0.38057324840764334,
   'recall': 0.3195187165775401,
   'specificity': 0.3195187165775401,
   'f1': 0.34738372093023256},
  {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
   'y_predicted': array([0., 1., 1., ..., 0., 1., 1.])}),
 'boost': ({'accuracy': 0.585595567867036,
   'precision': 0.0,
   'recall': 0.0,
   'specificity': 0.0,
   'f1': 0.0},
  {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
   'y_predicted': array([0, 0, 0, ..., 0, 0, 0])})}

In [138]:
result_dic_list_TM_S_Intubation

{'logistic_regression': ({'accuracy': 0.5526421944332393,
   'precision': 0.6294602012808783,
   'recall': 0.4942528735632184,
   'specificity': 0.4942528735632184,
   'f1': 0.5537223340040242},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 0, 0, ..., 1, 1, 0], dtype=int64)}),
 'svm': ({'accuracy': 0.6248487293263413,
   'precision': 0.6779661016949152,
   'recall': 0.632183908045977,
   'specificity': 0.632183908045977,
   'f1': 0.654275092936803},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 0, 0, ..., 1, 0, 0], dtype=int64)}),
 'tree': ({'accuracy': 0.5655506252521177,
   'precision': 0.5648949320148331,
   'recall': 0.9849137931034483,
   'specificity': 0.9849137931034483,
   'f1': 0.7179890023566378},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
 'knn': ({'accuracy': 0.5320693828156515,
   'precision': 0.6076066790352505,
   'recall': 0.47054597701149425,
   'specificity': 0.47054597701149425,
   'f1': 0.5303643724696356},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 0, 0, ..., 1, 1, 1], dtype=int64)}),
 'forest': ({'accuracy': 0.5615167406212183,
   'precision': 0.5615167406212183,
   'recall': 1.0,
   'specificity': 1.0,
   'f1': 0.7191940067166107},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
 'neural': ({'accuracy': 0.5651472367890278,
   'precision': 0.594578313253012,
   'recall': 0.709051724137931,
   'specificity': 0.709051724137931,
   'f1': 0.6467889908256881},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([0, 1, 1, ..., 1, 1, 0], dtype=int64)}),
 'boost': ({'accuracy': 0.5615167406212183,
   'precision': 0.5615167406212183,
   'recall': 1.0,
   'specificity': 1.0,
   'f1': 0.7191940067166107},
  {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
   'y_predicted': array([1, 1, 1, ..., 1, 1, 1])})}

In [139]:

merged_dict = {}

# List of dictionary names and their corresponding dictionaries
dict_list = [('Outcome_InhospitalMortality', result_dic_list_Outcome_InhospitalMortality),
             ('TM_S_Intubation', result_dic_list_TM_S_Intubation),
             ('Outcome_ICUadmission', result_dic_list_Outcome_ICUadmission),
             ('TM_S_Dialysis', result_dic_list_TM_S_Dialysis)]

# Merge the dictionaries
for name, result_dict in dict_list:
    merged_dict[name] = result_dict

# The merged_dict now contains all the dictionaries merged together

In [140]:
merged_dict

{'Outcome_InhospitalMortality': {'logistic_regression': ({'accuracy': 0.6155124653739612,
    'precision': 0.5292207792207793,
    'recall': 0.6537433155080213,
    'specificity': 0.6537433155080213,
    'f1': 0.5849282296650719},
   {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
    'y_predicted': array([0., 1., 0., ..., 1., 1., 1.])}),
  'svm': ({'accuracy': 0.6415512465373961,
    'precision': 0.5575826681870011,
    'recall': 0.6537433155080213,
    'specificity': 0.6537433155080213,
    'f1': 0.6018461538461538},
   {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
    'y_predicted': array([0., 0., 1., ..., 1., 1., 1.])}),
  'tree': ({'accuracy': 0.5495844875346261,
    'precision': 0.04225352112676056,
    'recall': 0.004010695187165776,
    'specificity': 0.004010695187165776,
    'f1': 0.007326007326007327},
   {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
    'y_predicted': array([1., 0., 1., ..., 0., 0., 0.])}),
  'knn': ({'accuracy': 0.6271468144044321,
    'precision': 0.5389408099688473,
    'recall': 0.6938502673796791,
    'specificity': 0.6938502673796791,
    'f1': 0.6066627703097603},
   {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
    'y_predicted': array([0., 0., 0., ..., 1., 1., 1.])}),
  'forest': ({'accuracy': 0.585595567867036,
    'precision': 0.0,
    'recall': 0.0,
    'specificity': 0.0,
    'f1': 0.0},
   {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
    'y_predicted': array([0., 0., 0., ..., 0., 0., 0.])}),
  'neural': ({'accuracy': 0.5024930747922438,
    'precision': 0.38057324840764334,
    'recall': 0.3195187165775401,
    'specificity': 0.3195187165775401,
    'f1': 0.34738372093023256},
   {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
    'y_predicted': array([0., 1., 1., ..., 0., 1., 1.])}),
  'boost': ({'accuracy': 0.585595567867036,
    'precision': 0.0,
    'recall': 0.0,
    'specificity': 0.0,
    'f1': 0.0},
   {'y_true': array([0., 0., 0., ..., 1., 1., 1.]),
    'y_predicted': array([0, 0, 0, ..., 0, 0, 0])})},
 'TM_S_Intubation': {'logistic_regression': ({'accuracy': 0.5526421944332393,
    'precision': 0.6294602012808783,
    'recall': 0.4942528735632184,
    'specificity': 0.4942528735632184,
    'f1': 0.5537223340040242},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 0, 0, ..., 1, 1, 0], dtype=int64)}),
  'svm': ({'accuracy': 0.6248487293263413,
    'precision': 0.6779661016949152,
    'recall': 0.632183908045977,
    'specificity': 0.632183908045977,
    'f1': 0.654275092936803},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 0, 0, ..., 1, 0, 0], dtype=int64)}),
  'tree': ({'accuracy': 0.5655506252521177,
    'precision': 0.5648949320148331,
    'recall': 0.9849137931034483,
    'specificity': 0.9849137931034483,
    'f1': 0.7179890023566378},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
  'knn': ({'accuracy': 0.5320693828156515,
    'precision': 0.6076066790352505,
    'recall': 0.47054597701149425,
    'specificity': 0.47054597701149425,
    'f1': 0.5303643724696356},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 0, 0, ..., 1, 1, 1], dtype=int64)}),
  'forest': ({'accuracy': 0.5615167406212183,
    'precision': 0.5615167406212183,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.7191940067166107},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
  'neural': ({'accuracy': 0.5651472367890278,
    'precision': 0.594578313253012,
    'recall': 0.709051724137931,
    'specificity': 0.709051724137931,
    'f1': 0.6467889908256881},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 1, 1, ..., 1, 1, 0], dtype=int64)}),
  'boost': ({'accuracy': 0.5615167406212183,
    'precision': 0.5615167406212183,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.7191940067166107},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1])})},
 'Outcome_ICUadmission': {'logistic_regression': ({'accuracy': 0.6344086021505376,
    'precision': 0.6173752310536045,
    'recall': 0.792094861660079,
    'specificity': 0.792094861660079,
    'f1': 0.6939058171745152},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 1, 0, ..., 1, 1, 1], dtype=int64)}),
  'svm': ({'accuracy': 0.5851943755169562,
    'precision': 0.5707343412526998,
    'recall': 0.8355731225296442,
    'specificity': 0.8355731225296442,
    'f1': 0.6782162335579083},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 1, 1, ..., 1, 1, 1], dtype=int64)}),
  'tree': ({'accuracy': 0.6563275434243176,
    'precision': 0.603530534351145,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.7527521570961023},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 0, ..., 1, 1, 1], dtype=int64)}),
  'knn': ({'accuracy': 0.5529363110008272,
    'precision': 0.5807017543859649,
    'recall': 0.5233201581027668,
    'specificity': 0.5233201581027668,
    'f1': 0.5505197505197507},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 1, 0, ..., 1, 0, 1], dtype=int64)}),
  'forest': ({'accuracy': 0.5231596360628619,
    'precision': 0.5231596360628619,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.6869399945696443},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
  'neural': ({'accuracy': 0.5268817204301075,
    'precision': 0.5359477124183006,
    'recall': 0.7130434782608696,
    'specificity': 0.7130434782608696,
    'f1': 0.6119402985074627},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 1, 0, ..., 1, 1, 1], dtype=int64)}),
  'boost': ({'accuracy': 0.5231596360628619,
    'precision': 0.5231596360628619,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.6869399945696443},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1])})},
 'TM_S_Dialysis': {'logistic_regression': ({'accuracy': 0.7908386662175817,
    'precision': 0.7212276214833759,
    'recall': 0.9488559892328399,
    'specificity': 0.9488559892328399,
    'f1': 0.8195292066259808},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 1, 0, ..., 1, 1, 1], dtype=int64)}),
  'svm': ({'accuracy': 0.28157628831256315,
    'precision': 0.0,
    'recall': 0.0,
    'specificity': 0.0,
    'f1': 0.0},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 0, 0, ..., 0, 0, 0], dtype=int64)}),
  'tree': ({'accuracy': 0.5018524755810037,
    'precision': 0.5011804384485666,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.6677151201977084},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
  'knn': ({'accuracy': 0.41562815762883126,
    'precision': 0.328748280605227,
    'recall': 0.16083445491251683,
    'specificity': 0.16083445491251683,
    'f1': 0.21599638499774065},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 0, 0, ..., 0, 0, 0], dtype=int64)}),
  'forest': ({'accuracy': 0.500505220613001,
    'precision': 0.500505220613001,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.6671156004489337},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1], dtype=int64)}),
  'neural': ({'accuracy': 0.38093634220276185,
    'precision': 0.310752688172043,
    'recall': 0.19448183041722747,
    'specificity': 0.19448183041722747,
    'f1': 0.2392384105960265},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([0, 0, 0, ..., 1, 0, 0], dtype=int64)}),
  'boost': ({'accuracy': 0.500505220613001,
    'precision': 0.500505220613001,
    'recall': 1.0,
    'specificity': 1.0,
    'f1': 0.6671156004489337},
   {'y_true': array([0, 0, 0, ..., 1, 1, 1], dtype=int64),
    'y_predicted': array([1, 1, 1, ..., 1, 1, 1])})}}

In [141]:
import pandas as pd


df = pd.DataFrame(merged_dict)


df = df.transpose()


df.reset_index(inplace=True)
df.rename(columns={'index': 'Method'}, inplace=True)

In [142]:
df

,Method,logistic_regression,svm,tree,knn,forest,neural,boost
0,Outcome_InhospitalMortality,"({'accuracy': 0.6155124653739612, 'precision':...","({'accuracy': 0.6415512465373961, 'precision':...","({'accuracy': 0.5495844875346261, 'precision':...","({'accuracy': 0.6271468144044321, 'precision':...","({'accuracy': 0.585595567867036, 'precision': ...","({'accuracy': 0.5024930747922438, 'precision':...","({'accuracy': 0.585595567867036, 'precision': ..."
1,TM_S_Intubation,"({'accuracy': 0.5526421944332393, 'precision':...","({'accuracy': 0.6248487293263413, 'precision':...","({'accuracy': 0.5655506252521177, 'precision':...","({'accuracy': 0.5320693828156515, 'precision':...","({'accuracy': 0.5615167406212183, 'precision':...","({'accuracy': 0.5651472367890278, 'precision':...","({'accuracy': 0.5615167406212183, 'precision':..."
2,Outcome_ICUadmission,"({'accuracy': 0.6344086021505376, 'precision':...","({'accuracy': 0.5851943755169562, 'precision':...","({'accuracy': 0.6563275434243176, 'precision':...","({'accuracy': 0.5529363110008272, 'precision':...","({'accuracy': 0.5231596360628619, 'precision':...","({'accuracy': 0.5268817204301075, 'precision':...","({'accuracy': 0.5231596360628619, 'precision':..."
3,TM_S_Dialysis,"({'accuracy': 0.7908386662175817, 'precision':...","({'accuracy': 0.28157628831256315, 'precision'...","({'accuracy': 0.5018524755810037, 'precision':...","({'accuracy': 0.41562815762883126, 'precision'...","({'accuracy': 0.500505220613001, 'precision': ...","({'accuracy': 0.38093634220276185, 'precision'...","({'accuracy': 0.500505220613001, 'precision': ..."

In [143]:
data = []

for outcome, models in merged_dict.items():
    for model, metrics in models.items():
        accuracy, precision, recall, specificity, f1 = metrics[0]['accuracy'], metrics[0]['precision'], metrics[0]['recall'], metrics[0]['specificity'], metrics[0]['f1']
        y_true, y_predicted = metrics[1]['y_true'], metrics[1]['y_predicted']
        data.append([outcome, model, accuracy, precision, recall, specificity, f1, y_true.tolist(), y_predicted.tolist()])

columns = ['Outcome', 'Model', 'Accuracy', 'Precision', 'Recall', 'Specificity', 'F1', 'y_true', 'y_predicted']

df = pd.DataFrame(data, columns=columns)

In [144]:
df

,Outcome,Model,Accuracy,Precision,Recall,Specificity,F1,y_true,y_predicted
0,Outcome_InhospitalMortality,logistic_regression,0.615512,0.529221,0.653743,0.653743,0.584928,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ..."
1,Outcome_InhospitalMortality,svm,0.641551,0.557583,0.653743,0.653743,0.601846,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, ..."
2,Outcome_InhospitalMortality,tree,0.549584,0.042254,0.004011,0.004011,0.007326,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,Outcome_InhospitalMortality,knn,0.627147,0.538941,0.693850,0.693850,0.606663,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ..."
4,Outcome_InhospitalMortality,forest,0.585596,0.000000,0.000000,0.000000,0.000000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,Outcome_InhospitalMortality,neural,0.502493,0.380573,0.319519,0.319519,0.347384,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, ..."
6,Outcome_InhospitalMortality,boost,0.585596,0.000000,0.000000,0.000000,0.000000,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,TM_S_Intubation,logistic_regression,0.552642,0.629460,0.494253,0.494253,0.553722,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, ..."
8,TM_S_Intubation,svm,0.624849,0.677966,0.632184,0.632184,0.654275,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, ..."
9,TM_S_Intubation,tree,0.565551,0.564895,0.984914,0.984914,0.717989,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
10,TM_S_Intubation,knn,0.532069,0.607607,0.470546,0.470546,0.530364,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, ..."
11,TM_S_Intubation,forest,0.561517,0.561517,1.000000,1.000000,0.719194,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
12,TM_S_Intubation,neural,0.565147,0.594578,0.709052,0.709052,0.646789,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, ..."
13,TM_S_Intubation,boost,0.561517,0.561517,1.000000,1.000000,0.719194,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
14,Outcome_ICUadmission,logistic_regression,0.634409,0.617375,0.792095,0.792095,0.693906,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, ..."
15,Outcome_ICUadmission,svm,0.585194,0.570734,0.835573,0.835573,0.678216,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, ..."
16,Outcome_ICUadmission,tree,0.656328,0.603531,1.000000,1.000000,0.752752,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, ..."
17,Outcome_ICUadmission,knn,0.552936,0.580702,0.523320,0.523320,0.550520,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, ..."
18,Outcome_ICUadmission,forest,0.523160,0.523160,1.000000,1.000000,0.686940,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
19,Outcome_ICUadmission,neural,0.526882,0.535948,0.713043,0.713043,0.611940,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, ..."
20,Outcome_ICUadmission,boost,0.523160,0.523160,1.000000,1.000000,0.686940,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
21,TM_S_Dialysis,logistic_regression,0.790839,0.721228,0.948856,0.948856,0.819529,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, ..."
22,TM_S_Dialysis,svm,0.281576,0.000000,0.000000,0.000000,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, ..."
23,TM_S_Dialysis,tree,0.501852,0.501180,1.000000,1.000000,0.667715,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
24,TM_S_Dialysis,knn,0.415628,0.328748,0.160834,0.160834,0.215996,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, ..."
25,TM_S_Dialysis,forest,0.500505,0.500505,1.000000,1.000000,0.667116,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
26,TM_S_Dialysis,neural,0.380936,0.310753,0.194482,0.194482,0.239238,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, ..."
27,TM_S_Dialysis,boost,0.500505,0.500505,1.000000,1.000000,0.667116,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [145]:

# Apply feature selection to both the training and test sets
X_train_selected_Mortality_ICU = X_train[selected_features]
X_test_selected_Mortality_ICU = X_test[selected_features]

NameError: name 'selected_features' is not defined