In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Train and Test sets

from google.colab import drive
drive.mount('/content/drive')

import os

# Set the search parameters
filename = "3.xlsx"
search_path = '/content/drive/My Drive'

# Search for the file
for root, dirs, files in os.walk(search_path):
    if filename in files:
        file_path = os.path.join(root, filename)
        break

import pandas as pd

# Load the XLSX file into a DataFrame
df = pd.read_excel(file_path)

## Training set (imputing and normalizing)

In [2]:
df = pd.read_excel("3.xlsx")

In [3]:
df.head()

,Patient_Hospital,Outcome_InhospitalMortality,Outcome_ICUadmission,TM_S_Intubation,TM_S_Dialysis,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,Hospital1,0.0,1,1,1,0.0,1.0,1,1,0,...,NaN,140.0,4.0,181.0,62.0,661.0,32.6,10.9,1.00,33.0
1,Hospital1,0.0,1,1,0,NaN,1.0,1,1,0,...,1.1,139.0,3.5,98.0,30.0,179.0,37.6,10.8,0.99,44.0
2,Hospital1,0.0,1,0,1,NaN,1.0,0,1,0,...,0.9,138.0,4.2,99.0,29.0,1956.0,27.4,12.1,1.11,50.0
3,Hospital1,1.0,1,0,0,NaN,1.0,0,1,1,...,1.2,137.0,4.7,139.0,20.0,30.0,29.1,14.2,1.31,71.0
4,Hospital1,1.0,1,0,0,NaN,1.0,0,1,1,...,1.2,137.0,4.7,139.0,20.0,30.0,29.1,14.2,1.31,71.0

In [4]:
# ooutcome columns: 1.are Outcome_InhospitalMortality 
df = df.dropna(subset=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])

In [5]:
#inja oomadim va external validation ro freeze kardim
df_internal_validation = df[df['Patient_Hospital']!="Hospital2"]
df_external_validation = df[df['Patient_Hospital']=="Hospital2"]
df_internal_validation = df_internal_validation.drop(columns=['Patient_Hospital'])
df_external_validation = df_external_validation.drop(columns=['Patient_Hospital'])

In [6]:
#df.to_excel("excluding NAN.xlsx", index=False)

In [7]:
#inja train test split kardim va target variable ro jodakardim
# Define features (X) and target variable (y)
X = df_internal_validation.drop(columns=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])
y  = df_internal_validation[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]
# Perform the train-test split (adjust the test_size as needed)
X_train , X_test , y_train , y_test = train_test_split(X,y , test_size = 0.2 , random_state = 42)

In [8]:
y_train

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
1513,1.0,0,0,0
216,0.0,0,0,0
5163,0.0,0,0,1
6924,1.0,0,0,0
421,0.0,0,1,0
...,...,...,...,...
6007,1.0,0,0,0
6173,1.0,0,0,0
860,1.0,0,0,0
9089,1.0,0,0,0
8082,1.0,0,0,0

In [9]:
X_train

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
1513,NaN,0.0,0,1,0,0,0,0,0.0,0,...,NaN,134.0,3.8,190.0,62.0,40.0,30.100000,11.400000,1.05,38.0
216,10.0,0.0,0,0,0,0,0,1,0.0,0,...,3.4,128.0,6.2,189.0,97.0,98.0,38.500000,12.000000,0.89,89.0
5163,10.0,0.0,0,0,0,0,0,1,1.0,0,...,2.7,125.0,3.8,197.0,52.0,538.0,35.900002,19.200001,1.78,80.0
6924,NaN,1.0,0,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0
421,0.0,0.0,1,1,0,0,0,0,0.0,0,...,1.4,134.0,5.1,201.0,7.0,191.0,20.300000,12.900000,1.19,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6007,NaN,1.0,0,0,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.0
6173,NaN,0.0,1,1,1,1,1,0,0.0,0,...,0.8,140.0,4.5,219.0,26.0,40.0,25.299999,10.900000,1.00,46.0
860,NaN,1.0,0,0,0,0,0,0,0.0,0,...,NaN,136.0,3.7,NaN,NaN,NaN,NaN,NaN,NaN,62.0
9089,NaN,1.0,0,0,0,0,0,1,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85.0
8082,NaN,1.0,1,1,0,0,1,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0

In [10]:
#inja miaim va data haye categorical va numerical ro moshakhas mikonim ke bade knn categorical ha ro round konim
cat_col=[]
num_col=[]
for i in range(len(X_train.columns)):
    if i <=52:
        cat_col.append(X_train.columns[i])
    else:
        num_col.append(X_train.columns[i])

In [11]:
from sklearn.impute import KNNImputer
X_train_array  =X_train.to_numpy()
imputer = KNNImputer(n_neighbors=5, weights="uniform")
imputed = imputer.fit_transform(X_train_array)

In [12]:
df_imputed = pd.DataFrame(imputed)
df_imputed.columns=pd.DataFrame(X_train).columns.tolist()

In [13]:
df_imputed

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,5.4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.000,134.0,3.800,190.0,62.0,40.0,30.100000,11.400000,1.050,38.0
1,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,3.400,128.0,6.200,189.0,97.0,98.0,38.500000,12.000000,0.890,89.0
2,10.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,2.700,125.0,3.800,197.0,52.0,538.0,35.900002,19.200001,1.780,80.0
3,5.6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.404,134.8,4.020,199.2,77.6,1794.6,29.620000,12.980000,1.142,66.0
4,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.400,134.0,5.100,201.0,7.0,191.0,20.300000,12.900000,1.190,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6113,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.720,137.8,9.900,220.0,45.4,3417.4,28.260000,37.780000,3.100,34.0
6114,5.2,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.800,140.0,4.500,219.0,26.0,40.0,25.299999,10.900000,1.000,46.0
6115,5.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.380,136.0,3.700,204.6,57.0,277.2,34.120000,13.080000,1.148,62.0
6116,5.8,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.480,139.8,3.840,166.2,44.6,1786.8,22.980000,12.560000,1.158,85.0
6117,5.4,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,2.020,138.2,4.328,202.6,47.2,2031.2,25.980000,12.840000,1.146,50.0

In [14]:
for i in cat_col:
    df_imputed[[i]] = df_imputed[[i]].round()

In [15]:
df_imputed.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [16]:
df_imputed.shape

(6118, 76)

In [17]:
y_train.shape

(6118, 4)

In [18]:
#miaim x , y ro be ham michaboonim ta betonim normilize konim
df_before_normalize = pd.concat([df_imputed , y_train], axis=1)

In [19]:
arr_tain =df_imputed.to_numpy()

In [20]:
from sklearn import preprocessing
transform = preprocessing.StandardScaler()
df_normalize = transform.fit_transform(arr_tain)
df_normalize =pd.DataFrame(df_normalize)
df_normalize.columns = df_imputed.columns.tolist()

In [21]:
X_train = df_normalize
y_train = df_before_normalize[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]

In [22]:
X_train

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,-0.276913,-1.073643,-0.964980,0.831820,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,0.582317,-0.648294,-0.175141,-0.177509,0.000308,-0.500701,-0.200719,-0.267859,-0.179126,-0.992162
1,3.033279,-1.073643,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,1.318554,-0.307016,-0.159078,...,0.771769,-1.840406,-0.023446,-0.184944,0.027163,-0.446407,-0.033888,-0.241869,-0.187715,1.496371
2,3.033279,-1.073643,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,1.318554,3.257163,-0.159078,...,0.440228,-2.436462,-0.175141,-0.125462,-0.007365,-0.034519,-0.085527,0.070008,-0.139942,1.057218
3,0.385125,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,-0.173598,-0.489345,-0.161236,-0.109105,0.012278,1.141795,-0.210252,-0.199419,-0.174188,0.374091
4,-3.587106,-1.073643,1.036291,0.831820,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,-0.175492,-0.648294,-0.092973,-0.095721,-0.041893,-0.359349,-0.395355,-0.202884,-0.171611,-0.796983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6113,1.047164,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,0.449700,0.106711,0.210417,0.045548,-0.012429,2.660912,-0.237263,0.874824,-0.069088,-1.187341
6114,-0.276913,-1.073643,1.036291,0.831820,1.178125,1.724908,1.568569,-0.758406,-0.307016,-0.159078,...,-0.459671,0.543819,-0.130897,0.038113,-0.027314,-0.500701,-0.296051,-0.289517,-0.181810,-0.601804
6115,-0.276913,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,-0.758406,-0.307016,-0.159078,...,0.288666,-0.250923,-0.181462,-0.068955,-0.003528,-0.278656,-0.120879,-0.195087,-0.173866,0.178912
6116,0.385125,0.931408,-0.964980,-1.202183,-0.848806,-0.579741,-0.637524,1.318554,3.257163,-0.159078,...,-0.137602,0.504082,-0.172613,-0.354468,-0.013043,1.134493,-0.342128,-0.217612,-0.173329,1.301192
6117,-0.276913,0.931408,1.036291,0.831820,-0.848806,-0.579741,1.568569,-0.758406,-0.307016,-0.159078,...,0.118159,0.186185,-0.141768,-0.083825,-0.011048,1.363278,-0.282546,-0.205483,-0.173973,-0.406625

In [23]:
y_train

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,0.0,0,0,0
2,0.0,0,0,1
3,1.0,0,0,0
4,0.0,0,1,0
...,...,...,...,...
6113,1.0,0,0,0
6114,1.0,0,0,0
6115,1.0,0,0,0
6116,1.0,0,0,0
6117,1.0,0,0,0

In [24]:
y.value_counts("Outcome_InhospitalMortality")

Outcome_InhospitalMortality
1.0    6115
0.0    1533
Name: count, dtype: int64

In [25]:
y.value_counts("Outcome_ICUadmission")

Outcome_ICUadmission
0    6387
1    1261
Name: count, dtype: int64

## Test set (imputing and normalizing)

In [26]:
y_test

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
3265,1.0,0,0,0
6728,1.0,0,0,0
2892,1.0,0,0,0
3984,1.0,0,0,0
1221,1.0,0,0,0
...,...,...,...,...
7528,1.0,0,0,0
7526,0.0,0,0,0
1192,1.0,0,0,0
3964,1.0,0,1,0
5508,1.0,0,0,0

In [27]:
X_test

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
3265,NaN,1.0,1,1,1,0,1,0,0.0,0,...,1.02,136.0,3.8,278.0,42.0,71.0,33.0,16.1,1.40,53.0
6728,NaN,0.0,0,0,0,0,0,0,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.0
2892,NaN,0.0,1,1,1,1,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0
3984,NaN,1.0,0,0,1,1,0,0,0.0,0,...,3.49,135.0,3.6,221.0,34.0,218.0,40.0,13.0,1.00,54.0
1221,NaN,1.0,0,1,0,0,1,0,0.0,0,...,1.20,137.0,3.9,100.0,17.0,232.0,35.6,14.0,1.28,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7528,NaN,1.0,1,1,1,1,1,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0
7526,NaN,1.0,0,1,0,0,0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.0
1192,NaN,0.0,1,1,1,0,0,1,0.0,0,...,1.00,133.0,3.8,184.0,14.0,259.0,25.8,10.6,0.97,75.0
3964,10.0,1.0,0,1,1,1,1,0,0.0,0,...,NaN,139.0,4.0,153.0,NaN,124.0,38.0,13.0,1.00,50.0
5508,NaN,0.0,1,1,0,0,1,1,0.0,0,...,0.90,140.0,5.1,NaN,NaN,102.0,NaN,NaN,NaN,43.0

In [28]:
#inja miaim va data haye categorical va numerical ro moshakhas mikonim ke bade knn categorical ha ro round konim
cat_col=[]
num_col=[]
for i in range(len(X_test.columns)):
    if i <=52:
        cat_col.append(X_test.columns[i])
    else:
        num_col.append(X_test.columns[i])

In [29]:
from sklearn.impute import KNNImputer
X_test_array  =X_test.to_numpy()
imputer = KNNImputer(n_neighbors=5, weights="uniform")
imputed_test = imputer.fit_transform(X_test_array)

In [30]:
df_imputed_test = pd.DataFrame(imputed_test)
df_imputed_test.columns=pd.DataFrame(X_test).columns.tolist()

In [31]:
df_imputed_test

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,6.4,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.020,136.0,3.80,278.0,42.0,71.0,33.00,16.10,1.400,53.0
1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,2.310,138.0,4.12,216.6,36.0,142.0,25.64,12.32,1.200,72.0
2,4.6,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.440,138.8,4.00,247.6,41.2,116.6,25.64,11.54,1.044,75.0
3,7.6,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,3.490,135.0,3.60,221.0,34.0,218.0,40.00,13.00,1.000,54.0
4,6.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.200,137.0,3.90,100.0,17.0,232.0,35.60,14.00,1.280,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,3.2,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.340,138.2,4.18,230.4,44.6,190.0,29.40,12.90,1.188,73.0
1526,4.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.340,135.6,4.12,336.4,28.8,212.6,23.86,11.98,1.100,83.0
1527,6.8,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.000,133.0,3.80,184.0,14.0,259.0,25.80,10.60,0.970,75.0
1528,10.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.124,139.0,4.00,153.0,27.2,124.0,38.00,13.00,1.000,50.0
1529,6.4,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.900,140.0,5.10,154.0,38.2,102.0,26.60,11.96,1.060,43.0

In [32]:
for i in cat_col:
    df_imputed_test[[i]] = df_imputed_test[[i]].round()

In [33]:
df_imputed_test.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)

In [34]:
df_imputed_test.shape

(1530, 76)

In [35]:
y_test.shape

(1530, 4)

In [36]:
#miaim x , y ro be ham michaboonim ta betonim normilize konim
df_test_before_normalize = pd.concat([df_imputed_test , y_test], axis=1)

In [37]:
df_test_before_normalize.shape

(1530, 80)

In [38]:
arr =df_test_before_normalize.to_numpy()

In [39]:
arr

array([[ 6.,  1.,  1., ...,  0.,  0.,  0.],
       [ 4.,  0.,  0., ...,  0.,  0.,  0.],
       [ 5.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 7.,  0.,  1., ...,  0.,  0.,  0.],
       [10.,  1.,  0., ...,  0.,  1.,  0.],
       [ 6.,  0.,  1., ...,  0.,  0.,  0.]])

In [40]:
from sklearn import preprocessing
transform = preprocessing.StandardScaler()
df_test_normalize = transform.fit_transform(arr)
df_test_normalize =pd.DataFrame(df_test_normalize)
df_test_normalize.columns = df_internal_validation.columns.tolist()
df_test_normalize

,Outcome_InhospitalMortality,Outcome_ICUadmission,TM_S_Intubation,TM_S_Dialysis,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,0.273437,0.923201,1.015811,0.858291,1.149652,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,...,0.197369,-0.372103,-0.134941,-0.054545,-0.167263,-0.319589,0.488740,-0.29173,-0.439827,-0.172075
1,-0.826059,-1.083188,-0.984435,-1.165106,-0.869828,-0.622195,-0.614115,-0.760886,3.295522,-0.128885,...,-0.098694,-0.247141,-0.267685,-0.231803,-0.178906,0.722315,0.488740,-0.29173,-0.439827,-0.172075
2,-0.276311,-1.083188,1.015811,0.858291,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,...,0.157894,-0.291846,-0.267685,-0.268380,-0.187988,0.886826,0.488740,-0.29173,-0.439827,-0.172075
3,1.372933,0.923201,-0.984435,-1.165106,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,...,-0.197382,-0.113379,-0.008690,-0.199915,-0.190549,-0.264752,0.488740,-0.29173,-0.439827,-0.172075
4,0.273437,0.923201,-0.984435,0.858291,-0.869828,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,...,-1.036230,-0.088739,-0.088048,-0.153022,-0.174249,-0.484100,0.488740,-0.29173,-0.439827,-0.172075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,-1.375807,0.923201,1.015811,0.858291,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,...,0.325664,-0.162660,-0.199870,-0.204605,-0.179605,0.777152,0.488740,-0.29173,-0.439827,-0.172075
1526,-0.826059,0.923201,-0.984435,0.858291,-0.869828,-0.622195,-0.614115,-0.760886,-0.303442,-0.128885,...,-0.453971,-0.122883,-0.299789,-0.247747,-0.184727,1.325522,-2.046079,-0.29173,-0.439827,-0.172075
1527,0.823185,-1.083188,1.015811,0.858291,1.149652,-0.622195,-0.614115,1.314257,-0.303442,-0.128885,...,-1.184262,-0.041218,-0.264799,-0.312460,-0.192295,0.886826,0.488740,-0.29173,-0.439827,-0.172075
1528,2.472429,0.923201,-0.984435,0.858291,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,...,-0.532921,-0.278821,-0.044762,-0.199915,-0.190549,-0.484100,0.488740,-0.29173,2.273622,-0.172075
1529,0.273437,-1.083188,1.015811,0.858291,-0.869828,-0.622195,1.628358,1.314257,-0.303442,-0.128885,...,0.009862,-0.317542,-0.250371,-0.248685,-0.187056,-0.867959,0.488740,-0.29173,-0.439827,-0.172075

In [41]:
X_test = df_test_normalize.drop(columns=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])
y_test = df_test_before_normalize[['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis']]

In [42]:
X_test

,L1_BloodGroup_First,Demographic_Gender,Symptom_Caugh,Symptom_Dyspnea,Symptom_Fever,Symptom_Chiver,Symptom_Mylagia,Symptom_Weakness,Symptom_LOC,Symptom_Sore through,...,LAB_CR_1,LAB_NA_First,LAB_K_First,LAB_ALKP_First,LAB_ESR_First,LAB_CPK_First,LAB_PTT_First,LAB_PT_First,LAB_INR_First,Demographic_Age
0,1.149652,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,2.279108,...,0.197369,-0.372103,-0.134941,-0.054545,-0.167263,-0.319589,0.488740,-0.29173,-0.439827,-0.172075
1,-0.869828,-0.622195,-0.614115,-0.760886,3.295522,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-0.098694,-0.247141,-0.267685,-0.231803,-0.178906,0.722315,0.488740,-0.29173,-0.439827,-0.172075
2,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,0.157894,-0.291846,-0.267685,-0.268380,-0.187988,0.886826,0.488740,-0.29173,-0.439827,-0.172075
3,1.149652,1.607214,-0.614115,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-0.197382,-0.113379,-0.008690,-0.199915,-0.190549,-0.264752,0.488740,-0.29173,-0.439827,-0.172075
4,-0.869828,-0.622195,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-1.036230,-0.088739,-0.088048,-0.153022,-0.174249,-0.484100,0.488740,-0.29173,-0.439827,-0.172075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1525,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,0.325664,-0.162660,-0.199870,-0.204605,-0.179605,0.777152,0.488740,-0.29173,-0.439827,-0.172075
1526,-0.869828,-0.622195,-0.614115,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,2.046079,-0.438768,...,-0.453971,-0.122883,-0.299789,-0.247747,-0.184727,1.325522,-2.046079,-0.29173,-0.439827,-0.172075
1527,1.149652,-0.622195,-0.614115,1.314257,-0.303442,-0.128885,-0.096098,-0.106,2.046079,2.279108,...,-1.184262,-0.041218,-0.264799,-0.312460,-0.192295,0.886826,0.488740,-0.29173,-0.439827,-0.172075
1528,1.149652,1.607214,1.628358,-0.760886,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,-0.532921,-0.278821,-0.044762,-0.199915,-0.190549,-0.484100,0.488740,-0.29173,2.273622,-0.172075
1529,-0.869828,-0.622195,1.628358,1.314257,-0.303442,-0.128885,-0.096098,-0.106,-0.488740,-0.438768,...,0.009862,-0.317542,-0.250371,-0.248685,-0.187056,-0.867959,0.488740,-0.29173,-0.439827,-0.172075

In [43]:
y_test

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,1.0,0,0,0
2,1.0,0,0,0
3,1.0,0,0,0
4,1.0,0,0,0
...,...,...,...,...
1525,1.0,0,0,0
1526,0.0,0,0,0
1527,1.0,0,0,0
1528,1.0,0,1,0
1529,1.0,0,0,0

>>>Now dataset is cleaned and normalized

In [44]:
y_train

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,0.0,0,0,0
2,0.0,0,0,1
3,1.0,0,0,0
4,0.0,0,1,0
...,...,...,...,...
6113,1.0,0,0,0
6114,1.0,0,0,0
6115,1.0,0,0,0
6116,1.0,0,0,0
6117,1.0,0,0,0

In [45]:
y_train_Mortality =pd.DataFrame(y_train.loc[ : ,'Outcome_InhospitalMortality'])

In [46]:
y_train_Mortality

      Outcome_InhospitalMortality
0                             1.0
1                             0.0
2                             0.0
3                             1.0
4                             0.0
...                           ...
6113                          1.0
6114                          1.0
6115                          1.0
6116                          1.0
6117                          1.0

[6118 rows x 1 columns]

In [47]:
y_test

,Outcome_InhospitalMortality,TM_S_Intubation,Outcome_ICUadmission,TM_S_Dialysis
0,1.0,0,0,0
1,1.0,0,0,0
2,1.0,0,0,0
3,1.0,0,0,0
4,1.0,0,0,0
...,...,...,...,...
1525,1.0,0,0,0
1526,0.0,0,0,0
1527,1.0,0,0,0
1528,1.0,0,1,0
1529,1.0,0,0,0

In [48]:
y_test_Mortality =pd.DataFrame(y_train.loc[ : ,'Outcome_InhospitalMortality'])

## data selection Mortality and ICU

In [49]:
'''from sklearn.linear_model import Lasso

def lasso_MO_ICU(X_train ,y_train,X_test):
    # Perform feature selection using LASSO on the training set
    lasso = Lasso(alpha=0.1)
    lasso.fit(X_train, y_train)

    # Get the absolute coefficients and sort them
    absolute_coeffs = np.abs(lasso.coef_)
    sorted_indices = np.argsort(absolute_coeffs)[::-1]
    
    
    X_train  = pd.DataFrame(X_train)
    X_test  = pd.DataFrame(X_test)
    # Select the top 2 features with the highest coefficients
    selected_features = X_train.columns[sorted_indices[:40]]

    # Apply feature selection to both the training and test sets
    X_train_selected_Mortality_ICU = X_train[selected_features]
    X_test_selected_Mortality_ICU = X_test[selected_features]
    
    return (pd.DataFrame(X_train_selected_Mortality_ICU), pd.DataFrame(X_test_selected_Mortality_ICU))

'''

'from sklearn.linear_model import Lasso\n\ndef lasso_MO_ICU(X_train ,y_train,X_test):\n    # Perform feature selection using LASSO on the training set\n    lasso = Lasso(alpha=0.1)\n    lasso.fit(X_train, y_train)\n\n    # Get the absolute coefficients and sort them\n    absolute_coeffs = np.abs(lasso.coef_)\n    sorted_indices = np.argsort(absolute_coeffs)[::-1]\n    \n    \n    X_train  = pd.DataFrame(X_train)\n    X_test  = pd.DataFrame(X_test)\n    # Select the top 2 features with the highest coefficients\n    selected_features = X_train.columns[sorted_indices[:40]]\n\n    # Apply feature selection to both the training and test sets\n    X_train_selected_Mortality_ICU = X_train[selected_features]\n    X_test_selected_Mortality_ICU = X_test[selected_features]\n    \n    return (pd.DataFrame(X_train_selected_Mortality_ICU), pd.DataFrame(X_test_selected_Mortality_ICU))\n\n'

In [50]:
from sklearn.linear_model import Lasso

def lasso_MO_ICU(X_train, y_train, X_test):
    # Perform feature selection using LASSO on the training set
    lasso = Lasso(alpha=0.1)
    lasso.fit(X_train, y_train)

    # Get the absolute coefficients and sort them
    absolute_coeffs = np.abs(lasso.coef_)
    sorted_indices = np.argsort(absolute_coeffs)[::-1]

    X_train = pd.DataFrame(X_train)
    X_test = pd.DataFrame(X_test)

    # Select the top 2 features with the highest coefficients
    selected_feature_indices = sorted_indices[:40]

    # Apply feature selection to both the training and test sets
    X_train_selected_Mortality_ICU = X_train.iloc[:, selected_feature_indices]
    X_test_selected_Mortality_ICU = X_test.iloc[:, selected_feature_indices]

    return X_train_selected_Mortality_ICU, X_test_selected_Mortality_ICU

## data selection Intubation and Dialysis

In [51]:
# ino aslan mindazim oon var va estefade nemikonim

from sklearn.linear_model import Lasso

def lasso_In_Dia(X_train ,y_train_Intubation):
    # Perform feature selection using LASSO on the training set
    lasso = Lasso(alpha=0.1)
    lasso.fit(X_train, y_train_Mortality)

    # Get the absolute coefficients and sort them
    absolute_coeffs = np.abs(lasso.coef_)
    sorted_indices = np.argsort(absolute_coeffs)[::-1]

    # Select the top 2 features with the highest coefficients
    selected_features = X_train.columns[sorted_indices[:10]]

    # Apply feature selection to both the training and test sets
    X_train_selected_In_Dia = X_train[selected_features]
    X_test_selected_In_Dia = X_test[selected_features]
    
    return X_train_selected_In_Dia, X_test_selected_In_Dia

# Undersampling and and Oversampling\

using **SMOTETomek**

In [52]:
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks
from imblearn.combine import SMOTEENN
from imblearn.ensemble import RUSBoostClassifier
def balancing_dataset(X_train,y_train , X_test , y_test):
    
    tl = TomekLinks()
    X_resampled_train , y_resampled_train = tl.fit_resample(X_train,y_train)
    X_resampled_test , y_resampled_test = tl.fit_resample(X_test,y_test)
    
    return (X_resampled_train, y_resampled_train,X_resampled_test , y_resampled_test )

# experimenting different models on dataset

In [53]:

import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [54]:
X_train = np.array(X_train)
X_test = np.array(X_test)

## Logistic Regression

In [55]:

#remember to consider x_test and y_test for each model

In [56]:
y_train_Outcome_InhospitalMortality = np.array(y_train['Outcome_InhospitalMortality'].tolist())
y_test_Outcome_InhospitalMortality = np.array(y_test['Outcome_InhospitalMortality'].tolist())

In [57]:
y_train_Outcome_InhospitalMortality.shape

(6118,)

In [58]:
X_train.shape

(6118, 76)

# define hyperparameters to tune
parameters_lr ={}

# define the model
lr = LogisticRegression(random_state = 12345)

# define the grid search object
grid_search_lr = GridSearchCV(
    estimator = lr,
    param_grid = parameters_lr,
    cv = 10,
    n_jobs=-1
)
# execute search
logreg_cv = grid_search_lr.fit(X_train,y_train_Outcome_InhospitalMortality)

best_classifier_lr = logreg_cv.best_estimator_

y_predicted_Mortality_lr = best_classifier_lr.predict(X_test)

from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score ,f1_score

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_lr)

Logistic_Regression = {}
Logistic_Regression["accuracy"]= accuracy
Logistic_Regression["precision"]= precision
Logistic_Regression["recall"]= recall
Logistic_Regression["specificity"]= accuracy
Logistic_Regression["f1"]= f1


y_plot = {}
y_plot["y_true"]= y_train_Outcome_InhospitalMortality
y_plot["y_predicted"]=y_test_Outcome_InhospitalMortality

In [59]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)
def logistic_regression_classifier(X_train, y_train, X_test, y_test):

    parameters_lr = {}


    lr = LogisticRegression(random_state=12345)


    grid_search_lr = GridSearchCV(
        estimator=lr,
        param_grid=parameters_lr,
        cv=5,
        n_jobs=-1
    )

    logreg_cv = grid_search_lr.fit(X_train, y_train)

    
    best_classifier_lr = logreg_cv.best_estimator_

 
    y_predicted_Mortality_lr = best_classifier_lr.predict(X_test)

 
    accuracy = accuracy_score(y_test, y_predicted_Mortality_lr)
    cm = confusion_matrix(y_test, y_predicted_Mortality_lr)
    precision = precision_score(y_test, y_predicted_Mortality_lr)
    recall = recall_score(y_test, y_predicted_Mortality_lr)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_lr)


    Logistic_Regression = {}
    Logistic_Regression["accuracy"] = accuracy
    Logistic_Regression["precision"] = precision
    Logistic_Regression["recall"] = recall
    Logistic_Regression["specificity"] = specificity
    Logistic_Regression["f1"] = f1

    y_plot = {}
    y_plot["y_true"] = y_train
    y_plot["y_predicted"] = y_predicted_Mortality_lr
    
    Logistic_Regression = (Logistic_Regression, y_plot)
    
    return Logistic_Regression

## SVM

from sklearn import svm
svm = svm.SVC(random_state = 1234)

# define hyperparameters to tune
parameters_svm = {}

# define the grid search object
grid_search_svm = GridSearchCV(
    estimator = svm,
    param_grid = parameters_svm,
    cv = 10
)
# execute search
svm_cv = grid_search_svm.fit(X_train,y_train_Outcome_InhospitalMortality)

best_classifier_svm = svm_cv.best_estimator_

y_predicted_Mortality_svm = best_classifier_svm.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_svm)

svm = {}
svm["accuracy"]= accuracy
svm["precision"]= precision
svm["recall"]= recall
svm["specificity"]= accuracy
svm["f1"]= f1

y_plot = {}
y_plot["y_true"]= y_train_Outcome_InhospitalMortality
y_plot["y_predicted"]=y_test_Outcome_InhospitalMortality

In [60]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_svm(X_train, y_train, X_test, y_test):

    svm_classifier = svm.SVC(random_state=1234)


    parameters_svm = {}


    grid_search_svm = GridSearchCV(
        estimator=svm_classifier,
        param_grid=parameters_svm,
        cv=5
    )
    
   
    svm_cv = grid_search_svm.fit(X_train, y_train)

 
    best_classifier_svm = svm_cv.best_estimator_


    y_predicted_Mortality_svm = best_classifier_svm.predict(X_test)

   
    accuracy = accuracy_score(y_test, y_predicted_Mortality_svm)
    cm = confusion_matrix(y_test, y_predicted_Mortality_svm)
    precision = precision_score(y_test, y_predicted_Mortality_svm)
    recall = recall_score(y_test, y_predicted_Mortality_svm)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_svm)

    svm_results = {}
    svm_results["accuracy"] = accuracy
    svm_results["precision"] = precision
    svm_results["recall"] = recall
    svm_results["specificity"] = specificity
    svm_results["f1"] = f1

  
    y_plot = {}
    y_plot["y_true"] = y_train  
    y_plot["y_predicted"] = y_predicted_Mortality_svm

    svm_results = (svm_results, y_plot)
    
    return svm_results

## Decision tree

# define hyperparameters to tune
parameters_tree = {}

# define the model
tree = DecisionTreeClassifier(random_state = 12345)

# define the grid search object
grid_search_tree = GridSearchCV(
    estimator = tree,
    param_grid = parameters_tree,
    cv = 10
)
# execute search
tree_cv = grid_search_tree.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_tree = tree_cv.best_estimator_

y_predicted_Mortality_tree = best_classifier_tree.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_tree)

tree = {}
tree["accuracy"]= accuracy
tree["precision"]= precision
tree["recall"]= recall
tree["specificity"]= accuracy
tree["f1"]= f1

In [61]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_tree(X_train, y_train, X_test, y_test):

    parameters_tree = {}

 
    tree = DecisionTreeClassifier(random_state=12345)

 
    grid_search_tree = GridSearchCV(
        estimator=tree,
        param_grid=parameters_tree,
        cv=5
    )
    

    tree_cv = grid_search_tree.fit(X_train, y_train)

  
    best_classifier_tree = tree_cv.best_estimator_

 
    y_predicted_Mortality_tree = best_classifier_tree.predict(X_test)

 
    accuracy = accuracy_score(y_test, y_predicted_Mortality_tree)
    cm = confusion_matrix(y_test, y_predicted_Mortality_tree)
    precision = precision_score(y_test, y_predicted_Mortality_tree)
    recall = recall_score(y_test, y_predicted_Mortality_tree)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_tree)

  
    tree_results = {}
    tree_results["accuracy"] = accuracy
    tree_results["precision"] = precision
    tree_results["recall"] = recall
    tree_results["specificity"] = specificity
    tree_results["f1"] = f1


    y_plot = {}
    y_plot["y_true"] = y_train 
    y_plot["y_predicted"] = y_predicted_Mortality_tree

    tree_results = (tree_results, y_plot)
    
    return tree_results

## KNN

# define hyperparameters to tune
parameters_knn = {}

# define the model
knn = KNeighborsClassifier()

# define the grid search object
grid_search_knn = GridSearchCV(
    estimator = knn,
    param_grid = parameters_knn,
    cv = 10
)
# execute search
knn_cv = grid_search_knn.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_knn = knn_cv.best_estimator_

y_predicted_Mortality_Knn = best_classifier_knn.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_Knn)

Knn = {}
Knn["accuracy"]= accuracy
Knn["precision"]= precision
Knn["recall"]= recall
Knn["specificity"]= accuracy
Knn["f1"]= f1

In [62]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_knn(X_train, y_train, X_test, y_test):

    parameters_knn = {}

 
    knn = KNeighborsClassifier()


    grid_search_knn = GridSearchCV(
        estimator=knn,
        param_grid=parameters_knn,
        cv=5
    )
    

    knn_cv = grid_search_knn.fit(X_train, y_train)

    best_classifier_knn = knn_cv.best_estimator_

    y_predicted_Mortality_knn = best_classifier_knn.predict(X_test)

    accuracy = accuracy_score(y_test, y_predicted_Mortality_knn)
    cm = confusion_matrix(y_test, y_predicted_Mortality_knn)
    precision = precision_score(y_test, y_predicted_Mortality_knn)
    recall = recall_score(y_test, y_predicted_Mortality_knn)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_knn)

    knn_results = {}
    knn_results["accuracy"] = accuracy
    knn_results["precision"] = precision
    knn_results["recall"] = recall
    knn_results["specificity"] = specificity
    knn_results["f1"] = f1


    y_plot = {}
    y_plot["y_true"] = y_train  
    y_plot["y_predicted"] = y_predicted_Mortality_knn

    knn_results = (knn_results, y_plot)
    
    return knn_results

In [63]:
X_train

array([[-0.27691345, -1.07364303, -0.96498024, ..., -0.26785864,
        -0.17912625, -0.99216208],
       [ 3.03327893, -1.07364303, -0.96498024, ..., -0.24186888,
        -0.1877146 ,  1.49637106],
       [ 3.03327893, -1.07364303, -0.96498024, ...,  0.07000826,
        -0.13994187,  1.05721816],
       ...,
       [-0.27691345,  0.93140827, -0.96498024, ..., -0.19508732,
        -0.17386588,  0.17891234],
       [ 0.38512503,  0.93140827, -0.96498024, ..., -0.21761177,
        -0.17332911,  1.30119199],
       [-0.27691345,  0.93140827,  1.03629065, ..., -0.20548321,
        -0.17397323, -0.40662487]])

In [64]:
y_test['TM_S_Intubation']

0       0
1       0
2       0
3       0
4       0
       ..
1525    0
1526    0
1527    0
1528    0
1529    0
Name: TM_S_Intubation, Length: 1530, dtype: int64

In [65]:
X_test

array([[ 1.14965192, -0.62219452,  1.62835847, ..., -0.29172998,
        -0.43982694, -0.17207467],
       [-0.86982849, -0.62219452, -0.61411539, ..., -0.29172998,
        -0.43982694, -0.17207467],
       [ 1.14965192,  1.60721441, -0.61411539, ..., -0.29172998,
        -0.43982694, -0.17207467],
       ...,
       [ 1.14965192, -0.62219452, -0.61411539, ..., -0.29172998,
        -0.43982694, -0.17207467],
       [ 1.14965192,  1.60721441,  1.62835847, ..., -0.29172998,
         2.27362152, -0.17207467],
       [-0.86982849, -0.62219452,  1.62835847, ..., -0.29172998,
        -0.43982694, -0.17207467]])

## Random forest

from sklearn.ensemble import RandomForestClassifier

parameters_forest = {}

forest = RandomForestClassifier

grid_search_forest = GridSearchCV(
    estimator = forest,
    param_grid = parameters_forest,
    cv = 10
)
# execute search
forest_cv = grid_search_knn.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_forest = forest_cv.best_estimator_

y_predicted_Mortality_forest = best_classifier_forest.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_forest)

forest = {}
forest["accuracy"]= accuracy
forest["precision"]= precision
forest["recall"]= recall
forest["specificity"]= accuracy
forest["f1"]= f1

In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_forest(X_train, y_train, X_test, y_test):
    parameters_forest = {}


    forest = RandomForestClassifier()


    grid_search_forest = GridSearchCV(
        estimator=forest,
        param_grid=parameters_forest,
        cv=5
    )
    

    forest_cv = grid_search_forest.fit(X_train, y_train)

    best_classifier_forest = forest_cv.best_estimator_

    y_predicted_Mortality_forest = best_classifier_forest.predict(X_test)


    accuracy = accuracy_score(y_test, y_predicted_Mortality_forest)
    cm = confusion_matrix(y_test, y_predicted_Mortality_forest)
    precision = precision_score(y_test, y_predicted_Mortality_forest)
    recall = recall_score(y_test, y_predicted_Mortality_forest)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_forest)


    forest_results = {}
    forest_results["accuracy"] = accuracy
    forest_results["precision"] = precision
    forest_results["recall"] = recall
    forest_results["specificity"] = specificity
    forest_results["f1"] = f1

    y_plot = {}
    y_plot["y_true"] = y_train
    y_plot["y_predicted"] = y_predicted_Mortality_forest

    return forest_results, y_plot

## Neural Network

from sklearn.neural_network import MLPClassifier

parameters_neural = {}

neural = MLPClassifier()

grid_search_neural = GridSearchCV(
    estimator = neural,
    param_grid = parameters_neural,
    cv = 10
)

neural_cv = grid_search_neural.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_neural = neural_cv.best_estimator_

y_predicted_Mortality_neural =best_classifier_neural.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_neural)

neural = {}
neural["accuracy"]= accuracy
neural["precision"]= precision
neural["recall"]= recall
neural["specificity"]= accuracy
neural["f1"]= f1

In [67]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_neural(X_train, y_train, X_test, y_test):

    parameters_neural = {}


    neural = MLPClassifier()

    grid_search_neural = GridSearchCV(
        estimator=neural,
        param_grid=parameters_neural,
        cv=5
    )
    

    neural_cv = grid_search_neural.fit(X_train, y_train)

   
    best_classifier_neural = neural_cv.best_estimator_

    
    y_predicted_Mortality_neural = best_classifier_neural.predict(X_test)

    accuracy = accuracy_score(y_test, y_predicted_Mortality_neural)
    cm = confusion_matrix(y_test, y_predicted_Mortality_neural)
    precision = precision_score(y_test, y_predicted_Mortality_neural)
    recall = recall_score(y_test, y_predicted_Mortality_neural)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_neural)

 
    neural_results = {}
    neural_results["accuracy"] = accuracy
    neural_results["precision"] = precision
    neural_results["recall"] = recall
    neural_results["specificity"] = specificity
    neural_results["f1"] = f1

    
    y_plot = {}
    y_plot["y_true"] = y_train  
    y_plot["y_predicted"] = y_predicted_Mortality_neural

    return neural_results, y_plot

## XGboost

from xgboost import XGBClassifier
# Define a parameter grid to search through
parameters_boost = {}

# Create an XGBoost classifier
boost = XGBClassifier()

grid_search_boost = GridSearchCV(
    estimator = boost,
    param_grid = parameters_boost,
    cv = 10
)

boost_cv = grid_search_boost.fit(X_train, y_train_Outcome_InhospitalMortality)

best_classifier_boost = boost_cv.best_estimator_

y_predicted_Mortality_boost =best_classifier_boost.predict(X_test)

accuracy = accuracy_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)



cm = confusion_matrix(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)

precision = precision_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)
recall = recall_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)
specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])

f1 = f1_score(y_test_Outcome_InhospitalMortality, y_predicted_Mortality_boost)

boost = {}
boost["accuracy"]= accuracy
boost["precision"]= precision
boost["recall"]= recall
boost["specificity"]= accuracy
boost["f1"]= f1

In [68]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

def train_and_evaluate_boost(X_train, y_train, X_test, y_test):
  
    parameters_boost = {}

 
    boost = XGBClassifier()


    grid_search_boost = GridSearchCV(
        estimator=boost,
        param_grid=parameters_boost,
        cv=5
    )
    

    boost_cv = grid_search_boost.fit(X_train, y_train)


    best_classifier_boost = boost_cv.best_estimator_


    y_predicted_Mortality_boost = best_classifier_boost.predict(X_test)


    accuracy = accuracy_score(y_test, y_predicted_Mortality_boost)
    cm = confusion_matrix(y_test, y_predicted_Mortality_boost)
    precision = precision_score(y_test, y_predicted_Mortality_boost)
    recall = recall_score(y_test, y_predicted_Mortality_boost)
    specificity = cm[1, 1] / (cm[1, 0] + cm[1, 1])
    f1 = f1_score(y_test, y_predicted_Mortality_boost)

  
    boost_results = {}
    boost_results["accuracy"] = accuracy
    boost_results["precision"] = precision
    boost_results["recall"] = recall
    boost_results["specificity"] = specificity
    boost_results["f1"] = f1


    y_plot = {}
    y_plot["y_true"] = y_train 
    y_plot["y_predicted"] = y_predicted_Mortality_boost

    return boost_results, y_plot

final_Mortality_dict={'Logistic_Regression':Logistic_Regression,
                      'svm':svm,
                      'tree':tree,
                      'Knn':Knn,
                      'forest':forest,
                      'neural':neural,
                      'boost':boost}

final_Mortality_dict

df_con = pd.DataFrame.from_dict(final_Mortality_dict, orient='index')

df_con

max(df_con['f1'])

# Final results

In [69]:
list_Outcome_InhospitalMortality=[]


X_train = df_normalize
y_train = df_before_normalize.loc[:,'Outcome_InhospitalMortality']
X_test = df_test_normalize.drop(columns=['Outcome_InhospitalMortality', 'TM_S_Intubation', 'Outcome_ICUadmission','TM_S_Dialysis'])
y_test = df_test_before_normalize.loc[:,'Outcome_InhospitalMortality']
y_train_ = pd.DataFrame(y_train)
y_test_ = pd.DataFrame(y_test)
X_train, X_test = lasso_MO_ICU(pd.DataFrame(X_train), y_train_ ,pd.DataFrame(X_test))

In [70]:
X_train

,Symptom_LOC,Demographic_Age,MH_DM,MH_Opiumuser,Symptom_Earpain,Symptom_Hemorrhasia,Symptom_Hemiparesia,MH_PregnanAcy,MH_CurremtSmoker,MH_Alcoholuser,...,Symptom_Rhinorrhea,Symptom_Smelling disorder,Symptom_nauseaVomit,Symptom_Anorexia,Symptom_Diarhhea,Symptom_ChestPain,Symptom_Seizure,MH_Pneumonia,MH_CVA,MH_GIdisorder
0,-0.307016,-0.992162,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,1.958664,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003
1,-0.307016,1.496371,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,1.958664,-0.433013,3.138075,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003
2,3.257163,1.057218,1.659329,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003
3,-0.307016,0.374091,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003
4,-0.307016,-0.796983,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6113,-0.307016,-1.187341,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003
6114,-0.307016,-0.601804,1.659329,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,4.442858,-0.102003
6115,-0.307016,0.178912,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,2.309401,-0.318667,-0.316484,-0.081124,-0.072512,4.442858,-0.102003
6116,3.257163,1.301192,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003
6117,-0.307016,-0.406625,-0.602653,-0.203376,-0.040462,-0.042441,-0.073642,-0.066579,-0.234541,-0.065329,...,-0.102818,-0.100354,-0.510552,-0.433013,-0.318667,-0.316484,-0.081124,-0.072512,-0.225080,-0.102003

In [71]:
X_train.to_excel("features after selection for LLM model.xlsx", index=False)

In [72]:

X_train=np.array(X_train)
X_test=np.array(X_test)

y_train_ = np.array(y_train)
y_test_ = np.array(y_test)

X_train,y_train_ , X_test , y_test_ = balancing_dataset(X_train,y_train_ , X_test , y_test_)

list_Outcome_InhospitalMortality.extend([logistic_regression_classifier(X_train, y_train_, X_test, y_test_),
                                            train_and_evaluate_svm(X_train, y_train_, X_test, y_test_),
                                        train_and_evaluate_tree(X_train, y_train_, X_test, y_test_),
                                        train_and_evaluate_knn(X_train, y_train_, X_test, y_test_),
                                        train_and_evaluate_forest(X_train, y_train_, X_test, y_test_),
                                        train_and_evaluate_neural(X_train, y_train_, X_test, y_test_),
                                        train_and_evaluate_boost(X_train, y_train_, X_test, y_test_)])


result_dic_list_Outcome_InhospitalMortality = dict(zip(['logistic_regression', 'svm', 'tree', 'knn', 'forest', 'neural', 'boost'], list_Outcome_InhospitalMortality))



merged_dict = {}

# List of dictionary names and their corresponding dictionaries
dict_list = [('Outcome_InhospitalMortality', result_dic_list_Outcome_InhospitalMortality)]

# Merge the dictionaries
for name, result_dict in dict_list:
    merged_dict[name] = result_dict

# The merged_dict now contains all the dictionaries merged together


df = pd.DataFrame(merged_dict)


df = df.transpose()


df.reset_index(inplace=True)
df.rename(columns={'index': 'Method'}, inplace=True)


data = []

for outcome, models in merged_dict.items():
    for model, metrics in models.items():
        accuracy, precision, recall, specificity, f1 = metrics[0]['accuracy'], metrics[0]['precision'], metrics[0]['recall'], metrics[0]['specificity'], metrics[0]['f1']
        y_true, y_predicted = metrics[1]['y_true'], metrics[1]['y_predicted']
        data.append([outcome, model, accuracy, precision, recall, specificity, f1, y_true.tolist(), y_predicted.tolist()])

columns = ['Outcome', 'Model', 'Accuracy', 'Precision', 'Recall', 'Specificity', 'F1', 'y_true', 'y_predicted']

df = pd.DataFrame(data, columns=columns)

d:\python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
d:\python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(